const DATABASE = {

  // ══ DRAGON BALL Z ══════════════════════════════════════════════
  "Dragon Ball Z": {
    emoji: "🔥",
    sagas: {
      "Saga Saiyajin": [
        { nome: "Vegeta",      poder: 18000, emoji: "🔵", tipo: "ataque" },
        { nome: "Goku",        poder: 9000,  emoji: "🟠", tipo: "ataque" },
        { nome: "Nappa",       poder: 4000,  emoji: "🗿", tipo: "tank" },
        { nome: "Piccolo",     poder: 3500,  emoji: "🟢", tipo: "suporte" },
        { nome: "Gohan",       poder: 2800,  emoji: "🟡", tipo: "ataque" },
        { nome: "Tenshinhan",  poder: 1830,  emoji: "👁️", tipo: "ataque" },
        { nome: "Krilin",      poder: 1750,  emoji: "⚪", tipo: "suporte" },
        { nome: "Raditz",      poder: 1500,  emoji: "🌑", tipo: "ataque" },
        { nome: "Yamcha",      poder: 1200,  emoji: "❌", tipo: "ataque" },
        { nome: "Kami",        poder: 1000,  emoji: "👴", tipo: "suporte" },
        { nome: "Chaiotzu",    poder: 610,   emoji: "🎭", tipo: "suporte" },
      ],
      "Saga Freeza": [
        { nome: "Goku SSJ",    poder: 15000, emoji: "🟠", tipo: "ataque" },
        { nome: "Freeza",      poder: 13500, emoji: "👾", tipo: "ataque" },
        { nome: "Ginyu",       poder: 11000, emoji: "💜", tipo: "ataque" },
        { nome: "Vegeta",      poder: 10000, emoji: "🔵", tipo: "ataque" },
        { nome: "Piccolo",     poder: 9000,  emoji: "🟢", tipo: "suporte" },
        { nome: "Gohan",       poder: 7500,  emoji: "🟡", tipo: "ataque" },
        { nome: "Recoome",     poder: 7000,  emoji: "💪", tipo: "tank" },
        { nome: "Krilin",      poder: 5500,  emoji: "⚪", tipo: "suporte" },
        { nome: "Zarbon",      poder: 5000,  emoji: "💙", tipo: "ataque" },
        { nome: "Nail",        poder: 4500,  emoji: "💚", tipo: "ataque" },
        { nome: "Dodoria",     poder: 2500,  emoji: "🌸", tipo: "ataque" },
      ],
      "Saga Cell": [
        { nome: "Gohan SSJ2",    poder: 25000, emoji: "🟡", tipo: "ataque" },
        { nome: "Cell Perfeito", poder: 22000, emoji: "🦟", tipo: "ataque" },
        { nome: "Goku SSJ",      poder: 20000, emoji: "🟠", tipo: "ataque" },
        { nome: "Vegeta SSJ",    poder: 19000, emoji: "🔵", tipo: "ataque" },
        { nome: "Trunks SSJ",    poder: 17000, emoji: "💜", tipo: "ataque" },
        { nome: "Android 16",    poder: 15000, emoji: "🤖", tipo: "tank" },
        { nome: "Android 17",    poder: 13500, emoji: "⚙️", tipo: "ataque" },
        { nome: "Android 18",    poder: 13000, emoji: "🤖", tipo: "ataque" },
        { nome: "Piccolo",       poder: 12000, emoji: "🟢", tipo: "suporte" },
        { nome: "Krilin",        poder: 7000,  emoji: "⚪", tipo: "suporte" },
        { nome: "Tenshinhan",    poder: 5000,  emoji: "👁️", tipo: "ataque" },
      ],
      "Saga Majin Buu": [
        { nome: "Vegetto",       poder: 45000, emoji: "⚡", tipo: "ataque" },
        { nome: "Kid Buu",       poder: 40000, emoji: "😈", tipo: "ataque" },
        { nome: "Goku SSJ3",     poder: 38000, emoji: "🟠", tipo: "ataque" },
        { nome: "Gohan Místico", poder: 36000, emoji: "🟡", tipo: "ataque" },
        { nome: "Gotenks",       poder: 32000, emoji: "✨", tipo: "ataque" },
        { nome: "Buu Gordo",     poder: 28000, emoji: "🟣", tipo: "tank" },
        { nome: "Vegeta SSJ2",   poder: 24000, emoji: "🔵", tipo: "ataque" },
        { nome: "Dabura",        poder: 20000, emoji: "👹", tipo: "ataque" },
        { nome: "Piccolo",       poder: 15000, emoji: "🟢", tipo: "suporte" },
        { nome: "Kaioshin",      poder: 12000, emoji: "👑", tipo: "suporte" },
        { nome: "Babidi",        poder: 3000,  emoji: "🧙", tipo: "suporte" },
      ],
    }
  },

  // ══ DRAGON BALL (ORIGINAL) ══════════════════════════════════════
  "Dragon Ball": {
    emoji: "🌟",
    sagas: {
      "Saga do Torneio Budô": [
        { nome: "Mestre Roshi",   poder: 1200, emoji: "🐢", tipo: "ataque" },
        { nome: "Goku (criança)", poder: 1100, emoji: "🟠", tipo: "ataque" },
        { nome: "Tenshinhan",     poder: 1000, emoji: "👁️", tipo: "ataque" },
        { nome: "Chaiotzu",       poder: 850,  emoji: "🎭", tipo: "suporte" },
        { nome: "Krilin",         poder: 800,  emoji: "⚪", tipo: "suporte" },
        { nome: "Yamcha",         poder: 750,  emoji: "❌", tipo: "ataque" },
        { nome: "Nam",            poder: 600,  emoji: "🧘", tipo: "ataque" },
        { nome: "Giran",          poder: 500,  emoji: "🦎", tipo: "tank" },
        { nome: "Ranfan",         poder: 400,  emoji: "💃", tipo: "ataque" },
        { nome: "Bacterian",      poder: 300,  emoji: "🦠", tipo: "ataque" },
        { nome: "Bulma",          poder: 100,  emoji: "💙", tipo: "suporte" },
      ],
      "Saga da Red Ribbon": [
        { nome: "Goku (criança)", poder: 1800, emoji: "🟠", tipo: "ataque" },
        { nome: "Tao Pai Pai",    poder: 1600, emoji: "☠️", tipo: "ataque" },
        { nome: "General Blue",   poder: 1000, emoji: "💛", tipo: "ataque" },
        { nome: "Murasaki",       poder: 700,  emoji: "🥷", tipo: "ataque" },
        { nome: "Mercenário Tao", poder: 600,  emoji: "🗡️", tipo: "ataque" },
        { nome: "General White",  poder: 500,  emoji: "❄️", tipo: "ataque" },
        { nome: "Muscle Tower",   poder: 450,  emoji: "🏯", tipo: "tank" },
        { nome: "Nam",            poder: 400,  emoji: "🧘", tipo: "ataque" },
        { nome: "Krilin",         poder: 950,  emoji: "⚪", tipo: "suporte" },
        { nome: "Bulma",          poder: 100,  emoji: "💙", tipo: "suporte" },
        { nome: "Olong",          poder: 80,   emoji: "🐷", tipo: "suporte" },
      ],
      "Saga de Piccolo Daimao": [
        { nome: "Goku (jovem)",      poder: 2600, emoji: "🟠", tipo: "ataque" },
        { nome: "Piccolo Daimao",    poder: 2400, emoji: "🟢", tipo: "ataque" },
        { nome: "Piccolo Jr.",       poder: 2200, emoji: "💚", tipo: "ataque" },
        { nome: "Tambourine",        poder: 1400, emoji: "👹", tipo: "ataque" },
        { nome: "Drum",              poder: 1200, emoji: "🥁", tipo: "ataque" },
        { nome: "Piano",             poder: 900,  emoji: "🎹", tipo: "ataque" },
        { nome: "Tenshinhan",        poder: 1800, emoji: "👁️", tipo: "ataque" },
        { nome: "Krilin",            poder: 1500, emoji: "⚪", tipo: "suporte" },
        { nome: "Yamcha",            poder: 1100, emoji: "❌", tipo: "ataque" },
        { nome: "Roshi (Kame-sennin)", poder: 1300, emoji: "🐢", tipo: "ataque" },
        { nome: "Chaiotzu",          poder: 700,  emoji: "🎭", tipo: "suporte" },
      ],
    }
  },

  // ══ DRAGON BALL SUPER ═══════════════════════════════════════════
  "Dragon Ball Super": {
    emoji: "⚡",
    sagas: {
      "Saga do Deus Destruidor": [
        { nome: "Beerus",          poder: 85000, emoji: "😺", tipo: "ataque" },
        { nome: "Goku SSJD",       poder: 60000, emoji: "🔴", tipo: "ataque" },
        { nome: "Whis",            poder: 99000, emoji: "👼", tipo: "suporte" },
        { nome: "Vegeta SSJ2",     poder: 38000, emoji: "🔵", tipo: "ataque" },
        { nome: "Gohan Místico",   poder: 36000, emoji: "🟡", tipo: "ataque" },
        { nome: "Majin Buu",       poder: 34000, emoji: "🟣", tipo: "tank" },
        { nome: "Gotenks SSJ3",    poder: 33000, emoji: "✨", tipo: "ataque" },
        { nome: "Piccolo",         poder: 25000, emoji: "🟢", tipo: "suporte" },
        { nome: "Android 18",      poder: 22000, emoji: "🤖", tipo: "ataque" },
        { nome: "Tenshinhan",       poder: 10000, emoji: "👁️", tipo: "ataque" },
        { nome: "Yamcha",          poder: 8000,  emoji: "❌", tipo: "ataque" },
      ],
      "Saga de Goku Black": [
        { nome: "Zamasu Fundido",   poder: 90000, emoji: "⚡", tipo: "ataque" },
        { nome: "Goku Black SSJ Rosé", poder: 82000, emoji: "🌹", tipo: "ataque" },
        { nome: "Goku SSB",         poder: 78000, emoji: "🔵", tipo: "ataque" },
        { nome: "Vegeta SSB",       poder: 76000, emoji: "🔵", tipo: "ataque" },
        { nome: "Trunks do Futuro SSJ2", poder: 55000, emoji: "💜", tipo: "ataque" },
        { nome: "Zamasu",           poder: 50000, emoji: "😇", tipo: "ataque" },
        { nome: "Mai (Futuro)",     poder: 3000,  emoji: "🔫", tipo: "suporte" },
        { nome: "Bulma (Futuro)",   poder: 1000,  emoji: "💙", tipo: "suporte" },
        { nome: "Beerus",           poder: 95000, emoji: "😺", tipo: "ataque" },
        { nome: "Whis",             poder: 99000, emoji: "👼", tipo: "suporte" },
        { nome: "Piccolo",          poder: 30000, emoji: "🟢", tipo: "suporte" },
      ],
      "Saga do Torneio do Poder": [
        { nome: "Jiren",            poder: 99000, emoji: "💪", tipo: "tank" },
        { nome: "Goku Ultra Instinto", poder: 98000, emoji: "⚪", tipo: "ataque" },
        { nome: "Vegeta SSB Evoluído", poder: 88000, emoji: "🔵", tipo: "ataque" },
        { nome: "Toppo (Destruidor)", poder: 85000, emoji: "🟤", tipo: "tank" },
        { nome: "Kefla SSJ2",       poder: 80000, emoji: "💚", tipo: "ataque" },
        { nome: "Hit",              poder: 75000, emoji: "🕐", tipo: "ataque" },
        { nome: "Gohan Renascido",  poder: 65000, emoji: "🟡", tipo: "ataque" },
        { nome: "Freeza Golden",    poder: 70000, emoji: "👾", tipo: "ataque" },
        { nome: "Android 17",       poder: 60000, emoji: "⚙️", tipo: "ataque" },
        { nome: "Cabba SSJ",        poder: 45000, emoji: "💚", tipo: "ataque" },
        { nome: "Ribrianne",        poder: 40000, emoji: "💗", tipo: "suporte" },
      ],
      "Saga de Broly": [
        { nome: "Gogeta SSB",       poder: 99000, emoji: "🔵", tipo: "ataque" },
        { nome: "Broly Lendário",   poder: 97000, emoji: "💚", tipo: "ataque" },
        { nome: "Goku SSB",         poder: 85000, emoji: "🔵", tipo: "ataque" },
        { nome: "Vegeta SSB Evoluído", poder: 84000, emoji: "🔵", tipo: "ataque" },
        { nome: "Beerus",           poder: 95000, emoji: "😺", tipo: "ataque" },
        { nome: "Whis",             poder: 99000, emoji: "👼", tipo: "suporte" },
        { nome: "Freeza Golden",    poder: 75000, emoji: "👾", tipo: "ataque" },
        { nome: "Paragas",          poder: 30000, emoji: "🧔", tipo: "suporte" },
        { nome: "Chilai",           poder: 8000,  emoji: "💋", tipo: "suporte" },
        { nome: "Lemo",             poder: 5000,  emoji: "🧓", tipo: "suporte" },
        { nome: "Berryblue",        poder: 4000,  emoji: "💙", tipo: "suporte" },
      ],
    }
  },

  // ══ NARUTO ════════════════════════════════════════════════════
  "Naruto": {
    emoji: "🍃",
    sagas: {
      "Chunin Exams": [
        { nome: "Jiraiya",    poder: 7800, emoji: "🐸", tipo: "ataque" },
        { nome: "Tsunade",    poder: 7500, emoji: "💪", tipo: "suporte" },
        { nome: "Orochimaru", poder: 7000, emoji: "🐍", tipo: "ataque" },
        { nome: "Kakashi",    poder: 6800, emoji: "🔴", tipo: "ataque" },
        { nome: "Gaara",      poder: 5500, emoji: "🏜️", tipo: "ataque" },
        { nome: "Rock Lee",   poder: 5000, emoji: "🥋", tipo: "ataque" },
        { nome: "Neji",       poder: 4500, emoji: "👁️", tipo: "ataque" },
        { nome: "Sasuke",     poder: 3500, emoji: "⚡", tipo: "ataque" },
        { nome: "Naruto",     poder: 3200, emoji: "🍃", tipo: "ataque" },
        { nome: "Sakura",     poder: 2100, emoji: "🌸", tipo: "suporte" },
        { nome: "Iruka",      poder: 1500, emoji: "📚", tipo: "suporte" },
      ],
      "Saga de Itachi": [
        { nome: "Itachi",        poder: 11000, emoji: "🌙", tipo: "ataque" },
        { nome: "Kisame",        poder: 10500, emoji: "🦈", tipo: "ataque" },
        { nome: "Jiraiya",       poder: 10000, emoji: "🐸", tipo: "ataque" },
        { nome: "Kakashi (MS)",  poder: 9000,  emoji: "🔴", tipo: "ataque" },
        { nome: "Orochimaru",    poder: 8500,  emoji: "🐍", tipo: "ataque" },
        { nome: "Sasuke (CS2)",  poder: 8000,  emoji: "⚡", tipo: "ataque" },
        { nome: "Tsunade",       poder: 9500,  emoji: "💪", tipo: "suporte" },
        { nome: "Naruto (Bijuu mode proto)", poder: 7000, emoji: "🍃", tipo: "ataque" },
        { nome: "Yamato",        poder: 6500,  emoji: "🌲", tipo: "tank" },
        { nome: "Sai",           poder: 5000,  emoji: "🖌️", tipo: "suporte" },
        { nome: "Kabuto",        poder: 7500,  emoji: "🧬", tipo: "suporte" },
      ],
      "Shippuden — Pain": [
        { nome: "Naruto Sábio",  poder: 16000, emoji: "🍃", tipo: "ataque" },
        { nome: "Pain Nagato",   poder: 15000, emoji: "🔵", tipo: "ataque" },
        { nome: "Jiraiya",       poder: 12000, emoji: "🐸", tipo: "ataque" },
        { nome: "Tsunade",       poder: 10000, emoji: "💪", tipo: "suporte" },
        { nome: "Kakashi",       poder: 9500,  emoji: "🔴", tipo: "ataque" },
        { nome: "Konan",         poder: 8500,  emoji: "📄", tipo: "suporte" },
        { nome: "Yamato",        poder: 7500,  emoji: "🌲", tipo: "tank" },
        { nome: "Shikamaru",     poder: 6500,  emoji: "🦌", tipo: "suporte" },
        { nome: "Hinata",        poder: 5500,  emoji: "💜", tipo: "suporte" },
        { nome: "Choji",         poder: 5500,  emoji: "🟤", tipo: "tank" },
        { nome: "Ino",           poder: 4500,  emoji: "🌺", tipo: "suporte" },
      ],
      "Quarta Grande Guerra": [
        { nome: "Madara",            poder: 32000, emoji: "😤", tipo: "ataque" },
        { nome: "Hashirama",         poder: 30000, emoji: "🌿", tipo: "ataque" },
        { nome: "Naruto Bijuu",      poder: 28000, emoji: "🍃", tipo: "ataque" },
        { nome: "Sasuke Rinnegan",   poder: 27000, emoji: "⚡", tipo: "ataque" },
        { nome: "Guy (8 portas)",    poder: 26000, emoji: "🥋", tipo: "ataque" },
        { nome: "Minato",            poder: 25000, emoji: "💛", tipo: "ataque" },
        { nome: "Obito",             poder: 22000, emoji: "🌀", tipo: "ataque" },
        { nome: "Kakashi (Susanoo)", poder: 17000, emoji: "🔴", tipo: "ataque" },
        { nome: "Bee",               poder: 16000, emoji: "🎤", tipo: "ataque" },
        { nome: "A (Raikage)",       poder: 14000, emoji: "⚡", tipo: "tank" },
        { nome: "Gaara",             poder: 13000, emoji: "🏜️", tipo: "ataque" },
      ],
      "Boruto — Era dos Otsutsuki": [
        { nome: "Naruto (Baryon)", poder: 55000, emoji: "🍃", tipo: "ataque" },
        { nome: "Isshiki Otsutsuki", poder: 52000, emoji: "👁️", tipo: "ataque" },
        { nome: "Momoshiki (Boruto)", poder: 48000, emoji: "💜", tipo: "ataque" },
        { nome: "Sasuke Adulto",   poder: 40000, emoji: "⚡", tipo: "ataque" },
        { nome: "Jigen",           poder: 45000, emoji: "⛩️", tipo: "ataque" },
        { nome: "Kawaki",          poder: 35000, emoji: "🔧", tipo: "ataque" },
        { nome: "Boruto",          poder: 30000, emoji: "💙", tipo: "ataque" },
        { nome: "Code",            poder: 38000, emoji: "🔩", tipo: "ataque" },
        { nome: "Delta",           poder: 22000, emoji: "💠", tipo: "ataque" },
        { nome: "Kashin Koji",     poder: 28000, emoji: "🐸", tipo: "ataque" },
        { nome: "Mitsuki (Sábio)", poder: 20000, emoji: "💚", tipo: "ataque" },
      ],
    }
  },

  // ══ ONE PIECE ═════════════════════════════════════════════════
  "One Piece": {
    emoji: "☠️",
    sagas: {
      "East Blue": [
        { nome: "Mihawk",  poder: 9500, emoji: "🦅", tipo: "ataque" },
        { nome: "Shanks",  poder: 9000, emoji: "🍺", tipo: "ataque" },
        { nome: "Arlong",  poder: 2500, emoji: "🦈", tipo: "ataque" },
        { nome: "Luffy",   poder: 2000, emoji: "👒", tipo: "ataque" },
        { nome: "Zoro",    poder: 1900, emoji: "⚔️", tipo: "ataque" },
        { nome: "Sanji",   poder: 1800, emoji: "🔥", tipo: "ataque" },
        { nome: "Krieg",   poder: 1200, emoji: "🗡️", tipo: "ataque" },
        { nome: "Buggy",   poder: 800,  emoji: "🤡", tipo: "ataque" },
        { nome: "Usopp",   poder: 700,  emoji: "🎯", tipo: "suporte" },
        { nome: "Nami",    poder: 600,  emoji: "🌊", tipo: "suporte" },
        { nome: "Coby",    poder: 300,  emoji: "💙", tipo: "suporte" },
      ],
      "Alabasta — Crocodile": [
        { nome: "Crocodile",    poder: 7000, emoji: "🏜️", tipo: "ataque" },
        { nome: "Mihawk",       poder: 9500, emoji: "🦅", tipo: "ataque" },
        { nome: "Luffy G2 proto", poder: 5000, emoji: "👒", tipo: "ataque" },
        { nome: "Zoro",         poder: 4500, emoji: "⚔️", tipo: "ataque" },
        { nome: "Sanji",        poder: 4200, emoji: "🔥", tipo: "ataque" },
        { nome: "Daz Bones",    poder: 3800, emoji: "🗡️", tipo: "ataque" },
        { nome: "Miss All Sunday", poder: 4000, emoji: "🌹", tipo: "ataque" },
        { nome: "Mr. 1",        poder: 3600, emoji: "⚙️", tipo: "ataque" },
        { nome: "Bon Clay",     poder: 3000, emoji: "🦢", tipo: "suporte" },
        { nome: "Usopp",        poder: 1500, emoji: "🎯", tipo: "suporte" },
        { nome: "Chopper",      poder: 2000, emoji: "🦌", tipo: "suporte" },
      ],
      "Enies Lobby — CP9": [
        { nome: "Rob Lucci",    poder: 9000,  emoji: "🐆", tipo: "ataque" },
        { nome: "Luffy G2",     poder: 8500,  emoji: "👒", tipo: "ataque" },
        { nome: "Zoro",         poder: 7500,  emoji: "⚔️", tipo: "ataque" },
        { nome: "Sanji",        poder: 7000,  emoji: "🔥", tipo: "ataque" },
        { nome: "Kaku",         poder: 6500,  emoji: "🦒", tipo: "ataque" },
        { nome: "Jabra",        poder: 6000,  emoji: "🐺", tipo: "ataque" },
        { nome: "Blueno",       poder: 5500,  emoji: "🚪", tipo: "ataque" },
        { nome: "Franky",       poder: 5000,  emoji: "🤖", tipo: "tank" },
        { nome: "Robin",        poder: 4800,  emoji: "🌺", tipo: "suporte" },
        { nome: "Kumadori",     poder: 4500,  emoji: "🎭", tipo: "ataque" },
        { nome: "Kalifa",       poder: 4000,  emoji: "🧼", tipo: "ataque" },
      ],
      "Marineford": [
        { nome: "Barba Branca",  poder: 16000, emoji: "🌊", tipo: "tank" },
        { nome: "Shanks",        poder: 15000, emoji: "🍺", tipo: "ataque" },
        { nome: "Mihawk",        poder: 13500, emoji: "🦅", tipo: "ataque" },
        { nome: "Akainu",        poder: 13000, emoji: "🌋", tipo: "ataque" },
        { nome: "Sengoku",       poder: 12500, emoji: "🦁", tipo: "ataque" },
        { nome: "Barba Negra",   poder: 12000, emoji: "🖤", tipo: "ataque" },
        { nome: "Aokiji",        poder: 11500, emoji: "❄️", tipo: "ataque" },
        { nome: "Kizaru",        poder: 11000, emoji: "💡", tipo: "ataque" },
        { nome: "Marco",         poder: 10000, emoji: "🐦", tipo: "suporte" },
        { nome: "Ace",           poder: 9000,  emoji: "🔥", tipo: "ataque" },
        { nome: "Luffy G2",      poder: 8000,  emoji: "👒", tipo: "ataque" },
      ],
      "Dressrosa — Doflamingo": [
        { nome: "Luffy G4",      poder: 18000, emoji: "👒", tipo: "ataque" },
        { nome: "Doflamingo",    poder: 17000, emoji: "🕊️", tipo: "ataque" },
        { nome: "Fujitora",      poder: 15000, emoji: "⚖️", tipo: "ataque" },
        { nome: "Zoro (Pica)",   poder: 13000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Law",           poder: 12000, emoji: "💛", tipo: "suporte" },
        { nome: "Sabo",          poder: 14000, emoji: "🔥", tipo: "ataque" },
        { nome: "Cavendish",     poder: 9000,  emoji: "🦁", tipo: "ataque" },
        { nome: "Kyros",         poder: 8000,  emoji: "🏅", tipo: "ataque" },
        { nome: "Bellamy",       poder: 7000,  emoji: "🌀", tipo: "ataque" },
        { nome: "Baby 5",        poder: 6500,  emoji: "💣", tipo: "ataque" },
        { nome: "Senor Pink",    poder: 6000,  emoji: "👶", tipo: "tank" },
      ],
      "Whole Cake — Big Mom": [
        { nome: "Big Mom",        poder: 21000, emoji: "👑", tipo: "ataque" },
        { nome: "Katakuri",       poder: 19000, emoji: "🍩", tipo: "ataque" },
        { nome: "Luffy G4 Snake", poder: 18500, emoji: "👒", tipo: "ataque" },
        { nome: "Smoothie",       poder: 14000, emoji: "🍹", tipo: "ataque" },
        { nome: "Cracker",        poder: 13500, emoji: "🍪", tipo: "tank" },
        { nome: "Sanji (Raid Suit)", poder: 13000, emoji: "🔥", tipo: "ataque" },
        { nome: "Jinbe",          poder: 12000, emoji: "🐋", tipo: "tank" },
        { nome: "Compote",        poder: 9000,  emoji: "🎶", tipo: "suporte" },
        { nome: "Pedro",          poder: 8500,  emoji: "🐆", tipo: "ataque" },
        { nome: "Brulee",         poder: 5000,  emoji: "🪞", tipo: "suporte" },
        { nome: "Perospero",      poder: 10000, emoji: "🍭", tipo: "ataque" },
      ],
      "Wano — Kaido": [
        { nome: "Luffy Gear 5",   poder: 24000, emoji: "👒", tipo: "ataque" },
        { nome: "Kaido",          poder: 23000, emoji: "🐉", tipo: "tank" },
        { nome: "Big Mom",        poder: 21000, emoji: "👑", tipo: "ataque" },
        { nome: "Zoro (Enma)",    poder: 17000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Sanji (Ifrit)",  poder: 16000, emoji: "🔥", tipo: "ataque" },
        { nome: "King",           poder: 15000, emoji: "🦅", tipo: "suporte" },
        { nome: "Kid",            poder: 14000, emoji: "🧲", tipo: "ataque" },
        { nome: "Law",            poder: 14000, emoji: "💛", tipo: "suporte" },
        { nome: "Yamato",         poder: 13500, emoji: "❄️", tipo: "tank" },
        { nome: "Queen",          poder: 13000, emoji: "🦠", tipo: "ataque" },
        { nome: "Marco",          poder: 12000, emoji: "🐦", tipo: "suporte" },
      ],
    }
  },

  // ══ BLEACH ════════════════════════════════════════════════════
  "Bleach": {
    emoji: "⚫",
    sagas: {
      "Soul Society": [
        { nome: "Aizen (velado)",     poder: 10000, emoji: "😊", tipo: "ataque" },
        { nome: "Zaraki Kenpachi",    poder: 9500,  emoji: "⚔️", tipo: "ataque" },
        { nome: "Urahara",            poder: 9000,  emoji: "🎩", tipo: "suporte" },
        { nome: "Byakuya",            poder: 8500,  emoji: "🌸", tipo: "ataque" },
        { nome: "Yoruichi",           poder: 8500,  emoji: "🐱", tipo: "ataque" },
        { nome: "Ichigo (Bankai)",    poder: 8000,  emoji: "🟠", tipo: "ataque" },
        { nome: "Toshiro",            poder: 7500,  emoji: "❄️", tipo: "ataque" },
        { nome: "Renji",              poder: 6000,  emoji: "🔴", tipo: "ataque" },
        { nome: "Rukia",              poder: 5000,  emoji: "❄️", tipo: "ataque" },
        { nome: "Chad",               poder: 4000,  emoji: "💪", tipo: "tank" },
        { nome: "Orihime",            poder: 3500,  emoji: "🌸", tipo: "suporte" },
      ],
      "Arrancar — Aizen": [
        { nome: "Aizen Transcendente", poder: 20000, emoji: "😇", tipo: "ataque" },
        { nome: "Yamamoto",            poder: 18000, emoji: "🔥", tipo: "ataque" },
        { nome: "Ichigo Hollow",       poder: 15000, emoji: "🟠", tipo: "ataque" },
        { nome: "Ulquiorra 2ª Etapa",  poder: 14000, emoji: "🖤", tipo: "ataque" },
        { nome: "Stark",               poder: 13500, emoji: "🐺", tipo: "ataque" },
        { nome: "Isshin",              poder: 13000, emoji: "👨", tipo: "ataque" },
        { nome: "Barragan",            poder: 12500, emoji: "💀", tipo: "ataque" },
        { nome: "Urahara",             poder: 12000, emoji: "🎩", tipo: "suporte" },
        { nome: "Halibel",             poder: 11500, emoji: "🌊", tipo: "ataque" },
        { nome: "Yoruichi",            poder: 11000, emoji: "⚡", tipo: "ataque" },
        { nome: "Grimmjow",            poder: 10500, emoji: "🐱", tipo: "ataque" },
      ],
      "TYBW — Quincy": [
        { nome: "Ichibe Hyosube",      poder: 28000, emoji: "⬛", tipo: "ataque" },
        { nome: "Yhwach",              poder: 27000, emoji: "👁️", tipo: "ataque" },
        { nome: "Ichigo (True Bankai)",poder: 25000, emoji: "🟠", tipo: "ataque" },
        { nome: "Zaraki Kenpachi",     poder: 24000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Yamamoto (Bankai)",   poder: 23000, emoji: "🔥", tipo: "ataque" },
        { nome: "Gerard Valkyrie",     poder: 20000, emoji: "⚡", tipo: "tank" },
        { nome: "Pernida",             poder: 19000, emoji: "🤚", tipo: "ataque" },
        { nome: "Aizen (Transcendente)", poder: 22000, emoji: "😇", tipo: "ataque" },
        { nome: "Byakuya",             poder: 16000, emoji: "🌸", tipo: "ataque" },
        { nome: "Lille Barro",         poder: 17000, emoji: "🎯", tipo: "ataque" },
        { nome: "Uryu Ishida",         poder: 14000, emoji: "🏹", tipo: "ataque" },
      ],
    }
  },

  // ══ ATTACK ON TITAN ═══════════════════════════════════════════
  "Attack on Titan": {
    emoji: "🗡️",
    sagas: {
      "Queda de Shiganshina": [
        { nome: "Titã Colossal",       poder: 8000, emoji: "💨", tipo: "ataque" },
        { nome: "Levi",                poder: 7500, emoji: "⚔️", tipo: "ataque" },
        { nome: "Titã Encouraçado",    poder: 7000, emoji: "🛡️", tipo: "tank" },
        { nome: "Annie (Titã Fêmea)",  poder: 6500, emoji: "❄️", tipo: "ataque" },
        { nome: "Mikasa",              poder: 5500, emoji: "🔴", tipo: "ataque" },
        { nome: "Eren (Titã)",         poder: 4500, emoji: "🟢", tipo: "ataque" },
        { nome: "Erwin",               poder: 4500, emoji: "🦅", tipo: "suporte" },
        { nome: "Hange",               poder: 4000, emoji: "🔬", tipo: "suporte" },
        { nome: "Ymir",                poder: 4000, emoji: "🦴", tipo: "ataque" },
        { nome: "Historia",            poder: 2500, emoji: "👑", tipo: "suporte" },
        { nome: "Armin",               poder: 2500, emoji: "💡", tipo: "suporte" },
      ],
      "Marley — Guerreiros": [
        { nome: "Eren (Ataque)",        poder: 14000, emoji: "🟢", tipo: "ataque" },
        { nome: "Zeke (Fera)",          poder: 13000, emoji: "🐒", tipo: "ataque" },
        { nome: "Levi",                 poder: 12000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Reiner (Encouraçado)", poder: 11000, emoji: "🛡️", tipo: "tank" },
        { nome: "Armin (Colossal)",     poder: 10000, emoji: "💡", tipo: "ataque" },
        { nome: "Gabi",                 poder: 6000,  emoji: "🔫", tipo: "ataque" },
        { nome: "Falco",                poder: 5500,  emoji: "🦅", tipo: "ataque" },
        { nome: "Mikasa",               poder: 9000,  emoji: "🔴", tipo: "ataque" },
        { nome: "Annie",                poder: 8500,  emoji: "❄️", tipo: "ataque" },
        { nome: "Pieck",                poder: 8000,  emoji: "🚂", tipo: "tank" },
        { nome: "Colt",                 poder: 5000,  emoji: "🔒", tipo: "suporte" },
      ],
      "Rumbling — Eren": [
        { nome: "Eren Rumbling",        poder: 20000, emoji: "🟢", tipo: "ataque" },
        { nome: "Armin (Colossal)",     poder: 15000, emoji: "💡", tipo: "ataque" },
        { nome: "Bertholdt (Colossal)", poder: 12000, emoji: "💨", tipo: "tank" },
        { nome: "Zeke",                 poder: 11500, emoji: "🐒", tipo: "ataque" },
        { nome: "Reiner",               poder: 10500, emoji: "🛡️", tipo: "tank" },
        { nome: "Annie",                poder: 9500,  emoji: "❄️", tipo: "ataque" },
        { nome: "Levi",                 poder: 9000,  emoji: "⚔️", tipo: "ataque" },
        { nome: "Pieck",                poder: 7500,  emoji: "🚂", tipo: "tank" },
        { nome: "Mikasa",               poder: 7500,  emoji: "🔴", tipo: "ataque" },
        { nome: "Falco",                poder: 7000,  emoji: "🦅", tipo: "ataque" },
        { nome: "Historia",             poder: 4000,  emoji: "👑", tipo: "suporte" },
      ],
    }
  },

  // ══ HUNTER x HUNTER ══════════════════════════════════════════
  "Hunter x Hunter": {
    emoji: "🃏",
    sagas: {
      "Exame Hunter": [
        { nome: "Netero",    poder: 9500, emoji: "🙏", tipo: "ataque" },
        { nome: "Hisoka",    poder: 7500, emoji: "🃏", tipo: "ataque" },
        { nome: "Illumi",    poder: 7000, emoji: "🪡", tipo: "ataque" },
        { nome: "Hanzo",     poder: 5000, emoji: "🥷", tipo: "ataque" },
        { nome: "Killua",    poder: 4500, emoji: "⚡", tipo: "ataque" },
        { nome: "Gon",       poder: 3500, emoji: "🟢", tipo: "ataque" },
        { nome: "Kurapika",  poder: 3500, emoji: "🔗", tipo: "ataque" },
        { nome: "Bodoro",    poder: 3000, emoji: "👴", tipo: "ataque" },
        { nome: "Leorio",    poder: 2000, emoji: "💼", tipo: "suporte" },
        { nome: "Satotz",    poder: 2000, emoji: "🎩", tipo: "ataque" },
        { nome: "Tonpa",     poder: 500,  emoji: "😅", tipo: "ataque" },
      ],
      "Saga Yorknew — Ladrões de Fantasmas": [
        { nome: "Chrollo Lucilfer", poder: 12000, emoji: "📖", tipo: "ataque" },
        { nome: "Hisoka",           poder: 11000, emoji: "🃏", tipo: "ataque" },
        { nome: "Zeno Zoldyck",     poder: 11500, emoji: "🕸️", tipo: "ataque" },
        { nome: "Silva Zoldyck",    poder: 11000, emoji: "⚡", tipo: "ataque" },
        { nome: "Uvogin",           poder: 10000, emoji: "💪", tipo: "tank" },
        { nome: "Illumi",           poder: 9500,  emoji: "🪡", tipo: "ataque" },
        { nome: "Kurapika (Nen)",   poder: 9000,  emoji: "🔗", tipo: "ataque" },
        { nome: "Killua",           poder: 7500,  emoji: "⚡", tipo: "ataque" },
        { nome: "Gon",              poder: 6500,  emoji: "🟢", tipo: "ataque" },
        { nome: "Kortopi",          poder: 5000,  emoji: "👁️", tipo: "suporte" },
        { nome: "Nobunaga",         poder: 8500,  emoji: "⚔️", tipo: "ataque" },
      ],
      "Ant Chimera": [
        { nome: "Meruem",            poder: 22000, emoji: "👑", tipo: "ataque" },
        { nome: "Gon SSJ (adulto)", poder: 19000, emoji: "🟢", tipo: "ataque" },
        { nome: "Neferpitou",        poder: 17000, emoji: "🐱", tipo: "ataque" },
        { nome: "Netero",            poder: 16000, emoji: "🙏", tipo: "ataque" },
        { nome: "Menthuthuyoupi",    poder: 14500, emoji: "👾", tipo: "tank" },
        { nome: "Killua (Godspeed)", poder: 13000, emoji: "⚡", tipo: "ataque" },
        { nome: "Shaiapouf",         poder: 13000, emoji: "🦋", tipo: "suporte" },
        { nome: "Hisoka",            poder: 10000, emoji: "🃏", tipo: "ataque" },
        { nome: "Morel",             poder: 8500,  emoji: "💨", tipo: "suporte" },
        { nome: "Knuckle",           poder: 8000,  emoji: "🥊", tipo: "suporte" },
        { nome: "Shoot",             poder: 7500,  emoji: "🏹", tipo: "ataque" },
      ],
      "Arco da Eleição": [
        { nome: "Hisoka",            poder: 14000, emoji: "🃏", tipo: "ataque" },
        { nome: "Chrollo (new)",     poder: 14000, emoji: "📖", tipo: "ataque" },
        { nome: "Illumi",            poder: 11000, emoji: "🪡", tipo: "ataque" },
        { nome: "Leorio (Nen)",      poder: 8000,  emoji: "💼", tipo: "suporte" },
        { nome: "Killua",            poder: 12000, emoji: "⚡", tipo: "ataque" },
        { nome: "Alluka",            poder: 20000, emoji: "✨", tipo: "suporte" },
        { nome: "Kurapika",          poder: 10000, emoji: "🔗", tipo: "ataque" },
        { nome: "Gon (recuperado)", poder: 9000,  emoji: "🟢", tipo: "ataque" },
        { nome: "Pariston",          poder: 9000,  emoji: "🦊", tipo: "suporte" },
        { nome: "Cheadle",           poder: 7000,  emoji: "🐕", tipo: "suporte" },
        { nome: "Ging",              poder: 13000, emoji: "🌍", tipo: "ataque" },
      ],
    }
  },

  // ══ DEMON SLAYER ══════════════════════════════════════════════
  "Demon Slayer": {
    emoji: "🌸",
    sagas: {
      "Saga da Seleção Final": [
        { nome: "Urokodaki",    poder: 5000, emoji: "🔴", tipo: "suporte" },
        { nome: "Tanjiro",      poder: 2500, emoji: "🌊", tipo: "ataque" },
        { nome: "Sabito",       poder: 4000, emoji: "🦊", tipo: "ataque" },
        { nome: "Makomo",       poder: 3500, emoji: "🌸", tipo: "suporte" },
        { nome: "Giyu",         poder: 8500, emoji: "💧", tipo: "ataque" },
        { nome: "Demon da Mão", poder: 5500, emoji: "✋", tipo: "ataque" },
        { nome: "Zenitsu",      poder: 2000, emoji: "⚡", tipo: "ataque" },
        { nome: "Inosuke",      poder: 2200, emoji: "🐗", tipo: "ataque" },
        { nome: "Aoi",          poder: 1200, emoji: "💙", tipo: "suporte" },
        { nome: "Kanao",        poder: 4500, emoji: "🌺", tipo: "ataque" },
        { nome: "Genya",        poder: 2800, emoji: "🔫", tipo: "ataque" },
      ],
      "Saga do Trem Mugen": [
        { nome: "Rengoku",      poder: 16000, emoji: "🔥", tipo: "ataque" },
        { nome: "Akaza",        poder: 15000, emoji: "💜", tipo: "ataque" },
        { nome: "Enmu",         poder: 10000, emoji: "💤", tipo: "ataque" },
        { nome: "Tanjiro (Hinokami)", poder: 8000, emoji: "🌊", tipo: "ataque" },
        { nome: "Inosuke",      poder: 6500,  emoji: "🐗", tipo: "ataque" },
        { nome: "Zenitsu",      poder: 6000,  emoji: "⚡", tipo: "ataque" },
        { nome: "Nezuko (explosão)", poder: 7500, emoji: "🌸", tipo: "ataque" },
        { nome: "Kanao",        poder: 7000,  emoji: "🌺", tipo: "ataque" },
        { nome: "Genya",        poder: 5500,  emoji: "🔫", tipo: "ataque" },
        { nome: "Giyu",         poder: 14000, emoji: "💧", tipo: "ataque" },
        { nome: "Shinobu",      poder: 12000, emoji: "🦋", tipo: "suporte" },
      ],
      "Saga do Distrito do Entretenimento": [
        { nome: "Gyutaro",       poder: 17000, emoji: "☠️", tipo: "ataque" },
        { nome: "Daki",          poder: 14000, emoji: "💋", tipo: "ataque" },
        { nome: "Tengen Uzui",   poder: 15000, emoji: "💎", tipo: "ataque" },
        { nome: "Tanjiro (Mark)", poder: 13000, emoji: "🌊", tipo: "ataque" },
        { nome: "Zenitsu (pleno)", poder: 12000, emoji: "⚡", tipo: "ataque" },
        { nome: "Inosuke",       poder: 11000, emoji: "🐗", tipo: "ataque" },
        { nome: "Nezuko (Awakened)", poder: 13500, emoji: "🌸", tipo: "ataque" },
        { nome: "Makio",         poder: 6000,  emoji: "🐉", tipo: "suporte" },
        { nome: "Suma",          poder: 5500,  emoji: "🌺", tipo: "suporte" },
        { nome: "Hinatsuru",     poder: 5000,  emoji: "🎋", tipo: "suporte" },
        { nome: "Kanao",         poder: 10000, emoji: "🌺", tipo: "ataque" },
      ],
      "Saga da Aldeia dos Ferreiros": [
        { nome: "Hantengu (clone)", poder: 20000, emoji: "😱", tipo: "ataque" },
        { nome: "Gyokko",          poder: 17000, emoji: "🐟", tipo: "ataque" },
        { nome: "Muichiro Tokito", poder: 19000, emoji: "🌫️", tipo: "ataque" },
        { nome: "Mitsuri Kanroji", poder: 18000, emoji: "💞", tipo: "ataque" },
        { nome: "Tanjiro (Mark)",  poder: 16000, emoji: "🌊", tipo: "ataque" },
        { nome: "Genya",           poder: 14000, emoji: "🔫", tipo: "ataque" },
        { nome: "Nezuko (Sol)",    poder: 17500, emoji: "🌸", tipo: "ataque" },
        { nome: "Haganezuka",      poder: 2000,  emoji: "🔨", tipo: "suporte" },
        { nome: "Inosuke",         poder: 12000, emoji: "🐗", tipo: "ataque" },
        { nome: "Kanao",           poder: 13000, emoji: "🌺", tipo: "ataque" },
        { nome: "Giyu",            poder: 18500, emoji: "💧", tipo: "ataque" },
      ],
      "Saga do Castelo Infinito": [
        { nome: "Muzan Kibutsuji",   poder: 35000, emoji: "🌑", tipo: "ataque" },
        { nome: "Kokushibo",         poder: 30000, emoji: "🌙", tipo: "ataque" },
        { nome: "Doma",              poder: 27000, emoji: "❄️", tipo: "ataque" },
        { nome: "Akaza",             poder: 25000, emoji: "💜", tipo: "ataque" },
        { nome: "Gyomei Himejima",   poder: 28000, emoji: "🪨", tipo: "tank" },
        { nome: "Sanemi Shinazugawa", poder: 24000, emoji: "💚", tipo: "ataque" },
        { nome: "Giyu Tomioka",      poder: 23000, emoji: "💧", tipo: "ataque" },
        { nome: "Mitsuri Kanroji",   poder: 22000, emoji: "💞", tipo: "ataque" },
        { nome: "Muichiro Tokito",   poder: 22500, emoji: "🌫️", tipo: "ataque" },
        { nome: "Tanjiro (Sol Hino)", poder: 26000, emoji: "🌊", tipo: "ataque" },
        { nome: "Nezuko (humana)",   poder: 18000, emoji: "🌸", tipo: "suporte" },
      ],
    }
  },

  // ══ JUJUTSU KAISEN ════════════════════════════════════════════
  "Jujutsu Kaisen": {
    emoji: "💀",
    sagas: {
      "Saga da Escola": [
        { nome: "Gojo Satoru",     poder: 30000, emoji: "👁️", tipo: "ataque" },
        { nome: "Ryomen Sukuna",   poder: 28000, emoji: "👹", tipo: "ataque" },
        { nome: "Yuji Itadori",    poder: 8000,  emoji: "🩸", tipo: "ataque" },
        { nome: "Megumi Fushiguro", poder: 7500, emoji: "🐕", tipo: "ataque" },
        { nome: "Nobara",          poder: 6500,  emoji: "🔨", tipo: "ataque" },
        { nome: "Nanami Kento",    poder: 9000,  emoji: "👔", tipo: "ataque" },
        { nome: "Mahito",          poder: 11000, emoji: "😈", tipo: "ataque" },
        { nome: "Suguru Geto",     poder: 13000, emoji: "👺", tipo: "ataque" },
        { nome: "Junpei",          poder: 4000,  emoji: "🎣", tipo: "suporte" },
        { nome: "Aoi Todo",        poder: 10000, emoji: "🌸", tipo: "ataque" },
        { nome: "Panda",           poder: 5000,  emoji: "🐼", tipo: "tank" },
      ],
      "Saga do Torneio de Kyoto": [
        { nome: "Gojo Satoru",     poder: 30000, emoji: "👁️", tipo: "ataque" },
        { nome: "Hanami",          poder: 16000, emoji: "🌿", tipo: "ataque" },
        { nome: "Mahito",          poder: 13000, emoji: "😈", tipo: "ataque" },
        { nome: "Yuji Itadori",    poder: 11000, emoji: "🩸", tipo: "ataque" },
        { nome: "Aoi Todo",        poder: 12000, emoji: "🌸", tipo: "ataque" },
        { nome: "Noritoshi Kamo",  poder: 8000,  emoji: "🩸", tipo: "ataque" },
        { nome: "Mai Zenin",       poder: 5500,  emoji: "🔫", tipo: "ataque" },
        { nome: "Maki Zenin",      poder: 9000,  emoji: "⚔️", tipo: "ataque" },
        { nome: "Megumi",          poder: 8500,  emoji: "🐕", tipo: "suporte" },
        { nome: "Nobara",          poder: 7500,  emoji: "🔨", tipo: "ataque" },
        { nome: "Mechamaru",       poder: 7000,  emoji: "🤖", tipo: "suporte" },
      ],
      "Saga de Shibuya": [
        { nome: "Sukuna (15 dedos)", poder: 32000, emoji: "👹", tipo: "ataque" },
        { nome: "Pseudo-Geto (Kenjaku)", poder: 22000, emoji: "🧠", tipo: "ataque" },
        { nome: "Mahito (amadurecido)", poder: 20000, emoji: "😈", tipo: "ataque" },
        { nome: "Choso",           poder: 15000, emoji: "🩸", tipo: "ataque" },
        { nome: "Nanami",          poder: 12000, emoji: "👔", tipo: "ataque" },
        { nome: "Yuji (Black Flash)", poder: 14000, emoji: "🩸", tipo: "ataque" },
        { nome: "Dagon",           poder: 18000, emoji: "🐙", tipo: "ataque" },
        { nome: "Naobito Zenin",   poder: 11000, emoji: "⚡", tipo: "ataque" },
        { nome: "Maki",            poder: 10000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Mei Mei",         poder: 10500, emoji: "🦅", tipo: "ataque" },
        { nome: "Nobara",          poder: 9000,  emoji: "🔨", tipo: "ataque" },
      ],
      "Saga do Culling Game": [
        { nome: "Sukuna (Megumi)", poder: 38000, emoji: "👹", tipo: "ataque" },
        { nome: "Gojo Satoru",     poder: 35000, emoji: "👁️", tipo: "ataque" },
        { nome: "Yuta Okkotsu",    poder: 30000, emoji: "💍", tipo: "ataque" },
        { nome: "Kenjaku",         poder: 25000, emoji: "🧠", tipo: "ataque" },
        { nome: "Kashimo",         poder: 22000, emoji: "⚡", tipo: "ataque" },
        { nome: "Hakari",          poder: 20000, emoji: "🎰", tipo: "tank" },
        { nome: "Yuji (evolução)", poder: 18000, emoji: "🩸", tipo: "ataque" },
        { nome: "Maki (God Body)", poder: 17000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Kinji Hakari",    poder: 19000, emoji: "🎲", tipo: "tank" },
        { nome: "Megumi",          poder: 16000, emoji: "🐕", tipo: "suporte" },
        { nome: "Angel",           poder: 14000, emoji: "😇", tipo: "suporte" },
      ],
    }
  },

  // ══ MY HERO ACADEMIA ══════════════════════════════════════════
  "My Hero Academia": {
    emoji: "🦸",
    sagas: {
      "Saga USJ": [
        { nome: "All Might",        poder: 28000, emoji: "💪", tipo: "tank" },
        { nome: "Nomu USJ",         poder: 20000, emoji: "🧟", tipo: "tank" },
        { nome: "Aizawa (Eraserhead)", poder: 9000, emoji: "🕶️", tipo: "suporte" },
        { nome: "Tomura Shigaraki", poder: 8000,  emoji: "🤚", tipo: "ataque" },
        { nome: "Kurogiri",         poder: 7000,  emoji: "🌫️", tipo: "suporte" },
        { nome: "Bakugo",           poder: 6500,  emoji: "💥", tipo: "ataque" },
        { nome: "Todoroki",         poder: 7000,  emoji: "🔥", tipo: "ataque" },
        { nome: "Izuku (5%)",       poder: 5000,  emoji: "🌀", tipo: "ataque" },
        { nome: "Iida",             poder: 5500,  emoji: "⚙️", tipo: "ataque" },
        { nome: "Thirteen",         poder: 6000,  emoji: "🕳️", tipo: "suporte" },
        { nome: "Present Mic",      poder: 5800,  emoji: "🎤", tipo: "suporte" },
      ],
      "Saga do Festival Esportivo": [
        { nome: "Todoroki",         poder: 10000, emoji: "🔥", tipo: "ataque" },
        { nome: "Izuku (8%)",       poder: 9500,  emoji: "🌀", tipo: "ataque" },
        { nome: "Bakugo",           poder: 9000,  emoji: "💥", tipo: "ataque" },
        { nome: "Tokoyami",         poder: 8500,  emoji: "🐦", tipo: "ataque" },
        { nome: "Shinso",           poder: 7000,  emoji: "💜", tipo: "suporte" },
        { nome: "Uraraka",          poder: 6500,  emoji: "🌸", tipo: "suporte" },
        { nome: "Iida",             poder: 8000,  emoji: "⚙️", tipo: "ataque" },
        { nome: "Momo",             poder: 7500,  emoji: "⚗️", tipo: "suporte" },
        { nome: "Kirishima",        poder: 7000,  emoji: "🪨", tipo: "tank" },
        { nome: "Mei Hatsume",      poder: 6000,  emoji: "🔧", tipo: "suporte" },
        { nome: "Kaminari",         poder: 6500,  emoji: "⚡", tipo: "ataque" },
      ],
      "Saga de Kamino — All for One": [
        { nome: "All Might (100%)", poder: 32000, emoji: "💪", tipo: "ataque" },
        { nome: "All for One",      poder: 30000, emoji: "😷", tipo: "ataque" },
        { nome: "Endeavor",         poder: 20000, emoji: "🔥", tipo: "ataque" },
        { nome: "Best Jeanist",     poder: 15000, emoji: "🧵", tipo: "suporte" },
        { nome: "Bakugo (resgatado)", poder: 12000, emoji: "💥", tipo: "ataque" },
        { nome: "Izuku (8%)",       poder: 11000, emoji: "🌀", tipo: "ataque" },
        { nome: "Tomura",           poder: 14000, emoji: "🤚", tipo: "ataque" },
        { nome: "Dabi",             poder: 13000, emoji: "🔵", tipo: "ataque" },
        { nome: "Toga",             poder: 9000,  emoji: "🩸", tipo: "suporte" },
        { nome: "Twice",            poder: 8500,  emoji: "🃏", tipo: "suporte" },
        { nome: "Compress",         poder: 8000,  emoji: "🔴", tipo: "suporte" },
      ],
      "Guerra de Liberação Paranormal": [
        { nome: "Endeavor (peak)",  poder: 28000, emoji: "🔥", tipo: "ataque" },
        { nome: "Tomura (Enhanced)", poder: 35000, emoji: "🤚", tipo: "ataque" },
        { nome: "High-End Nomu",    poder: 25000, emoji: "🧟", tipo: "tank" },
        { nome: "Dabi (Touya)",     poder: 22000, emoji: "🔵", tipo: "ataque" },
        { nome: "Hawks",            poder: 20000, emoji: "🦅", tipo: "ataque" },
        { nome: "Izuku (30%)",      poder: 18000, emoji: "🌀", tipo: "ataque" },
        { nome: "Bakugo",           poder: 17000, emoji: "💥", tipo: "ataque" },
        { nome: "Gigantomachia",    poder: 24000, emoji: "🗻", tipo: "tank" },
        { nome: "Re-Destro",        poder: 16000, emoji: "😤", tipo: "ataque" },
        { nome: "Curious",          poder: 10000, emoji: "📰", tipo: "suporte" },
        { nome: "Geten",            poder: 14000, emoji: "❄️", tipo: "ataque" },
      ],
      "Saga Final — Guerra Absoluta": [
        { nome: "Izuku (OFA full)", poder: 55000, emoji: "🌀", tipo: "ataque" },
        { nome: "All for One",      poder: 52000, emoji: "😷", tipo: "ataque" },
        { nome: "Tomura + AFO",     poder: 50000, emoji: "🤚", tipo: "ataque" },
        { nome: "Bakugo",           poder: 35000, emoji: "💥", tipo: "ataque" },
        { nome: "Todoroki (peak)",  poder: 32000, emoji: "🔥", tipo: "ataque" },
        { nome: "Endeavor",         poder: 30000, emoji: "🔥", tipo: "ataque" },
        { nome: "Hawks",            poder: 28000, emoji: "🦅", tipo: "ataque" },
        { nome: "Uraraka",          poder: 20000, emoji: "🌸", tipo: "suporte" },
        { nome: "Togata (Lemillion)", poder: 25000, emoji: "💛", tipo: "ataque" },
        { nome: "Ochaco vs Toga",   poder: 22000, emoji: "🩸", tipo: "ataque" },
        { nome: "Dabi",             poder: 29000, emoji: "🔵", tipo: "ataque" },
      ],
    }
  },

  // ══ ONE PUNCH MAN ═════════════════════════════════════════════
  "One Punch Man": {
    emoji: "👊",
    sagas: {
      "Saga dos Mestres da Luta": [
        { nome: "Saitama",       poder: 99999, emoji: "👊", tipo: "ataque" },
        { nome: "Boros",         poder: 35000, emoji: "👁️", tipo: "ataque" },
        { nome: "Metalcleave",   poder: 20000, emoji: "⚙️", tipo: "ataque" },
        { nome: "Genos",         poder: 15000, emoji: "🤖", tipo: "ataque" },
        { nome: "Bang",          poder: 18000, emoji: "👴", tipo: "ataque" },
        { nome: "Atomic Samurai", poder: 16000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Metal Bat",     poder: 12000, emoji: "⚾", tipo: "ataque" },
        { nome: "Silverfang",    poder: 17000, emoji: "🐺", tipo: "ataque" },
        { nome: "Child Emperor", poder: 10000, emoji: "🧒", tipo: "suporte" },
        { nome: "King",          poder: 8000,  emoji: "👑", tipo: "suporte" },
        { nome: "Tornado",       poder: 22000, emoji: "🌪️", tipo: "ataque" },
      ],
      "Saga da Associação de Monstros": [
        { nome: "Garou (Cosmic)", poder: 60000, emoji: "🐺", tipo: "ataque" },
        { nome: "Saitama",        poder: 99999, emoji: "👊", tipo: "ataque" },
        { nome: "Orochi",         poder: 40000, emoji: "🐉", tipo: "tank" },
        { nome: "Psykos",         poder: 35000, emoji: "🌀", tipo: "ataque" },
        { nome: "Tornado",        poder: 30000, emoji: "🌪️", tipo: "ataque" },
        { nome: "Blast",          poder: 55000, emoji: "⭐", tipo: "ataque" },
        { nome: "Genos (Upgr.)",  poder: 25000, emoji: "🤖", tipo: "ataque" },
        { nome: "Suiryu",         poder: 20000, emoji: "🐉", tipo: "ataque" },
        { nome: "Darkshine",      poder: 22000, emoji: "💎", tipo: "tank" },
        { nome: "Drive Knight",   poder: 18000, emoji: "🏍️", tipo: "ataque" },
        { nome: "Fuhrer Ugly",    poder: 28000, emoji: "👹", tipo: "ataque" },
      ],
    }
  },

  // ══ FULLMETAL ALCHEMIST: BROTHERHOOD ════════════════════════
  "Fullmetal Alchemist": {
    emoji: "⚗️",
    sagas: {
      "Saga de Ishval": [
        { nome: "Roy Mustang",    poder: 12000, emoji: "🔥", tipo: "ataque" },
        { nome: "Scar",           poder: 11000, emoji: "✝️", tipo: "ataque" },
        { nome: "Olivier Armstrong", poder: 10000, emoji: "🧊", tipo: "ataque" },
        { nome: "Edward Elric",   poder: 9000,  emoji: "⚡", tipo: "ataque" },
        { nome: "Alphonse",       poder: 8500,  emoji: "🛡️", tipo: "tank" },
        { nome: "Kimblee",        poder: 10500, emoji: "💣", tipo: "ataque" },
        { nome: "Bradley (Wrath)", poder: 13000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Riza Hawkeye",   poder: 7000,  emoji: "🔫", tipo: "suporte" },
        { nome: "Alex Armstrong", poder: 9500,  emoji: "💪", tipo: "tank" },
        { nome: "Fuhrer Bradley", poder: 13000, emoji: "👁️", tipo: "ataque" },
        { nome: "May Chang",      poder: 7500,  emoji: "🌸", tipo: "suporte" },
      ],
      "Saga de Briggs": [
        { nome: "Sloth",          poder: 15000, emoji: "💤", tipo: "tank" },
        { nome: "Greed/Ling",     poder: 14000, emoji: "💎", tipo: "ataque" },
        { nome: "Olivier",        poder: 11000, emoji: "🧊", tipo: "ataque" },
        { nome: "Hohenheim",      poder: 18000, emoji: "👨", tipo: "suporte" },
        { nome: "Edward",         poder: 10000, emoji: "⚡", tipo: "ataque" },
        { nome: "Alphonse",       poder: 9500,  emoji: "🛡️", tipo: "tank" },
        { nome: "Miles",          poder: 7000,  emoji: "🔫", tipo: "ataque" },
        { nome: "Buccaneer",      poder: 8000,  emoji: "🪝", tipo: "tank" },
        { nome: "Pride (Selim)", poder: 17000, emoji: "😈", tipo: "ataque" },
        { nome: "Envy",           poder: 13000, emoji: "😒", tipo: "ataque" },
        { nome: "Darius",         poder: 7500,  emoji: "🐻", tipo: "ataque" },
      ],
      "Batalha Final — Father": [
        { nome: "Father",         poder: 25000, emoji: "☀️", tipo: "ataque" },
        { nome: "Van Hohenheim",  poder: 22000, emoji: "👨", tipo: "suporte" },
        { nome: "Edward (pico)", poder: 18000, emoji: "⚡", tipo: "ataque" },
        { nome: "Alphonse (porta)", poder: 17000, emoji: "🛡️", tipo: "tank" },
        { nome: "Greed (final)",  poder: 16000, emoji: "💎", tipo: "ataque" },
        { nome: "Roy Mustang",    poder: 15000, emoji: "🔥", tipo: "ataque" },
        { nome: "Scar (yin-yang)", poder: 14000, emoji: "✝️", tipo: "ataque" },
        { nome: "Izumi Curtis",   poder: 12000, emoji: "🌊", tipo: "ataque" },
        { nome: "Olivier",        poder: 11000, emoji: "🧊", tipo: "ataque" },
        { nome: "May (alkahestria)", poder: 10000, emoji: "🌸", tipo: "suporte" },
        { nome: "Lan Fan",        poder: 9000,  emoji: "⚙️", tipo: "ataque" },
      ],
    }
  },

  // ══ YU YU HAKUSHO ═════════════════════════════════════════════
  "Yu Yu Hakusho": {
    emoji: "👻",
    sagas: {
      "Torneio das Trevas": [
        { nome: "Toguro (100%)",   poder: 18000, emoji: "💪", tipo: "ataque" },
        { nome: "Yusuke",          poder: 16000, emoji: "👊", tipo: "ataque" },
        { nome: "Hiei (Dragon)",   poder: 15000, emoji: "🐉", tipo: "ataque" },
        { nome: "Kurama (Rose)",   poder: 14000, emoji: "🌹", tipo: "ataque" },
        { nome: "Bui",             poder: 13500, emoji: "🪓", tipo: "tank" },
        { nome: "Karasu",          poder: 13000, emoji: "🐦", tipo: "ataque" },
        { nome: "Kuwabara",        poder: 11000, emoji: "⚡", tipo: "ataque" },
        { nome: "Elder Toguro",    poder: 10000, emoji: "🧬", tipo: "ataque" },
        { nome: "Genkai",          poder: 12000, emoji: "👵", tipo: "suporte" },
        { nome: "Chu",             poder: 9000,  emoji: "🥊", tipo: "ataque" },
        { nome: "Rinku",           poder: 7000,  emoji: "🪀", tipo: "ataque" },
      ],
      "Capítulo Negro — Sensui": [
        { nome: "Yusuke Mazoku",   poder: 28000, emoji: "👊", tipo: "ataque" },
        { nome: "Sensui (7 pesonalidades)", poder: 25000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Hiei (Jaou)",     poder: 20000, emoji: "🐉", tipo: "ataque" },
        { nome: "Kurama (Yoko)",   poder: 19000, emoji: "🦊", tipo: "ataque" },
        { nome: "Itsuki",          poder: 14000, emoji: "🌀", tipo: "suporte" },
        { nome: "Elder Toguro",    poder: 12000, emoji: "🧬", tipo: "ataque" },
        { nome: "Mitarai",         poder: 9000,  emoji: "💧", tipo: "suporte" },
        { nome: "Kuwabara",        poder: 13000, emoji: "⚡", tipo: "ataque" },
        { nome: "Sniper",          poder: 10000, emoji: "🔫", tipo: "ataque" },
        { nome: "Gamemaster",      poder: 8000,  emoji: "🎮", tipo: "suporte" },
        { nome: "Gourmet",         poder: 9500,  emoji: "🍽️", tipo: "ataque" },
      ],
      "Saga dos Três Reis": [
        { nome: "Raizen",          poder: 40000, emoji: "👑", tipo: "ataque" },
        { nome: "Yomi",            poder: 35000, emoji: "👂", tipo: "ataque" },
        { nome: "Mukuro",          poder: 34000, emoji: "🌍", tipo: "ataque" },
        { nome: "Yusuke (Raizen)", poder: 38000, emoji: "👊", tipo: "ataque" },
        { nome: "Kurama (Yoko)",   poder: 25000, emoji: "🦊", tipo: "ataque" },
        { nome: "Hiei",            poder: 24000, emoji: "🐉", tipo: "ataque" },
        { nome: "Kuwabara",        poder: 18000, emoji: "⚡", tipo: "ataque" },
        { nome: "Genkai",          poder: 16000, emoji: "👵", tipo: "suporte" },
        { nome: "Rinku (adulto)", poder: 12000, emoji: "🪀", tipo: "ataque" },
        { nome: "Chu",             poder: 13000, emoji: "🥊", tipo: "ataque" },
        { nome: "Touya",           poder: 14000, emoji: "❄️", tipo: "ataque" },
      ],
    }
  },

  // ══ SAINT SEIYA ════════════════════════════════════════════════
  "Saint Seiya": {
    emoji: "⭐",
    sagas: {
      "Saga do Santuário": [
        { nome: "Shaka (Virgem)",   poder: 18000, emoji: "🧘", tipo: "ataque" },
        { nome: "Saga (Gêmeos)",    poder: 17000, emoji: "♊", tipo: "ataque" },
        { nome: "Seiya (Pégaso)",   poder: 12000, emoji: "🐴", tipo: "ataque" },
        { nome: "Ikki (Fênix)",     poder: 13000, emoji: "🔥", tipo: "ataque" },
        { nome: "Aiolia (Leão)",    poder: 16000, emoji: "🦁", tipo: "ataque" },
        { nome: "Mu (Carneiro)",    poder: 15000, emoji: "🐑", tipo: "suporte" },
        { nome: "Deathmask (Câncer)", poder: 14000, emoji: "☠️", tipo: "ataque" },
        { nome: "Shiryu (Dragão)", poder: 11500, emoji: "🐉", tipo: "ataque" },
        { nome: "Hyoga (Cisne)",    poder: 11000, emoji: "❄️", tipo: "ataque" },
        { nome: "Shun (Andrômeda)", poder: 10500, emoji: "🔗", tipo: "tank" },
        { nome: "Afrodite (Peixes)", poder: 13500, emoji: "🌹", tipo: "ataque" },
      ],
      "Saga de Poseidon": [
        { nome: "Julian/Poseidon",  poder: 22000, emoji: "🌊", tipo: "ataque" },
        { nome: "Seiya (Pégaso)",   poder: 16000, emoji: "🐴", tipo: "ataque" },
        { nome: "Ikki (Fênix)",     poder: 17000, emoji: "🔥", tipo: "ataque" },
        { nome: "Shiryu (Dragão)", poder: 15000, emoji: "🐉", tipo: "ataque" },
        { nome: "Hyoga (Cisne)",    poder: 14500, emoji: "❄️", tipo: "ataque" },
        { nome: "Shun (Andrômeda)", poder: 14000, emoji: "🔗", tipo: "tank" },
        { nome: "Sorrento (Sereia)", poder: 16000, emoji: "🎵", tipo: "ataque" },
        { nome: "Krisaor Krishna",  poder: 18000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Scylla Io",        poder: 15000, emoji: "🐙", tipo: "ataque" },
        { nome: "Charybdis",        poder: 13000, emoji: "🌀", tipo: "ataque" },
        { nome: "Seadragon Kanon",  poder: 17500, emoji: "🐲", tipo: "ataque" },
      ],
      "Saga de Hades": [
        { nome: "Hypnos",           poder: 30000, emoji: "😴", tipo: "ataque" },
        { nome: "Thanatos",         poder: 29000, emoji: "⚰️", tipo: "ataque" },
        { nome: "Hades",            poder: 28000, emoji: "🖤", tipo: "ataque" },
        { nome: "Seiya (Sétimo Sentido)", poder: 24000, emoji: "🐴", tipo: "ataque" },
        { nome: "Ikki",             poder: 22000, emoji: "🔥", tipo: "ataque" },
        { nome: "Radamanthys",      poder: 20000, emoji: "👁️", tipo: "ataque" },
        { nome: "Minos",            poder: 19000, emoji: "🐂", tipo: "tank" },
        { nome: "Aiacos",           poder: 18000, emoji: "🦅", tipo: "ataque" },
        { nome: "Pandora",          poder: 16000, emoji: "📦", tipo: "suporte" },
        { nome: "Shiryu",           poder: 20000, emoji: "🐉", tipo: "ataque" },
        { nome: "Shun (Hades-corpo)", poder: 21000, emoji: "🔗", tipo: "ataque" },
      ],
    }
  },

  // ══ FAIRY TAIL ════════════════════════════════════════════════
  "Fairy Tail": {
    emoji: "🐉",
    sagas: {
      "Saga Phantom Lord": [
        { nome: "Erza Scarlet",    poder: 12000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Natsu",           poder: 11000, emoji: "🔥", tipo: "ataque" },
        { nome: "Jose Porla",      poder: 13000, emoji: "👻", tipo: "ataque" },
        { nome: "Gajeel",          poder: 11500, emoji: "🔩", tipo: "tank" },
        { nome: "Aria",            poder: 10500, emoji: "💨", tipo: "ataque" },
        { nome: "Makarov",         poder: 14000, emoji: "👴", tipo: "ataque" },
        { nome: "Gray",            poder: 9000,  emoji: "❄️", tipo: "ataque" },
        { nome: "Elfman",          poder: 7000,  emoji: "💪", tipo: "tank" },
        { nome: "Mirajane",        poder: 10000, emoji: "😇", tipo: "ataque" },
        { nome: "Lucy",            poder: 6000,  emoji: "⭐", tipo: "suporte" },
        { nome: "Juvia",           poder: 8000,  emoji: "💧", tipo: "suporte" },
      ],
      "Saga da Ilha Tenrou": [
        { nome: "Acnologia",       poder: 35000, emoji: "🐉", tipo: "ataque" },
        { nome: "Zeref",           poder: 30000, emoji: "🖤", tipo: "ataque" },
        { nome: "Gildarts",        poder: 22000, emoji: "💥", tipo: "ataque" },
        { nome: "Laxus",           poder: 20000, emoji: "⚡", tipo: "ataque" },
        { nome: "Makarov",         poder: 18000, emoji: "👴", tipo: "ataque" },
        { nome: "Natsu (Devil Slayer proto)", poder: 14000, emoji: "🔥", tipo: "ataque" },
        { nome: "Erza",            poder: 15000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Mirajane (Demon)", poder: 16000, emoji: "😈", tipo: "ataque" },
        { nome: "Hades",           poder: 19000, emoji: "🖤", tipo: "ataque" },
        { nome: "Gray",            poder: 11000, emoji: "❄️", tipo: "ataque" },
        { nome: "Cana (Fairy Glitter)", poder: 12000, emoji: "🃏", tipo: "suporte" },
      ],
      "Grandes Jogos Mágicos": [
        { nome: "Natsu (Dragon Force)", poder: 20000, emoji: "🔥", tipo: "ataque" },
        { nome: "Erza",            poder: 18000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Jura (Pedra)",    poder: 22000, emoji: "🪨", tipo: "ataque" },
        { nome: "Laxus",           poder: 21000, emoji: "⚡", tipo: "ataque" },
        { nome: "Gajeel (Shadow)", poder: 17000, emoji: "🔩", tipo: "tank" },
        { nome: "Sting",           poder: 16000, emoji: "⚪", tipo: "ataque" },
        { nome: "Rogue",           poder: 15500, emoji: "🖤", tipo: "ataque" },
        { nome: "Kagura",          poder: 17500, emoji: "⚔️", tipo: "ataque" },
        { nome: "Minerva",         poder: 16000, emoji: "👑", tipo: "ataque" },
        { nome: "Gray",            poder: 14000, emoji: "❄️", tipo: "ataque" },
        { nome: "Rufus",           poder: 13000, emoji: "📚", tipo: "ataque" },
      ],
      "Saga de Tartaros": [
        { nome: "Natsu E.N.D.",    poder: 28000, emoji: "😈", tipo: "ataque" },
        { nome: "Igneel",          poder: 35000, emoji: "🔥", tipo: "ataque" },
        { nome: "Mard Geer",       poder: 26000, emoji: "🌹", tipo: "ataque" },
        { nome: "Acnologia",       poder: 40000, emoji: "🐉", tipo: "ataque" },
        { nome: "Kyoka",           poder: 20000, emoji: "😈", tipo: "ataque" },
        { nome: "Silver (Gray pai)", poder: 22000, emoji: "❄️", tipo: "ataque" },
        { nome: "Erza",            poder: 24000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Gray (Devil Slayer)", poder: 23000, emoji: "❄️", tipo: "ataque" },
        { nome: "Mirajane Tahm",   poder: 21000, emoji: "😈", tipo: "ataque" },
        { nome: "Torafuzar",       poder: 18000, emoji: "🦈", tipo: "ataque" },
        { nome: "Laxus",           poder: 25000, emoji: "⚡", tipo: "ataque" },
      ],
      "Saga do Império de Alvarez": [
        { nome: "Natsu (God Slayer)", poder: 42000, emoji: "😈", tipo: "ataque" },
        { nome: "Acnologia (Dragão)", poder: 50000, emoji: "🐉", tipo: "ataque" },
        { nome: "Zeref",           poder: 45000, emoji: "🖤", tipo: "ataque" },
        { nome: "August",          poder: 44000, emoji: "🪄", tipo: "ataque" },
        { nome: "Irene (Dragonificação)", poder: 43000, emoji: "🧬", tipo: "ataque" },
        { nome: "Erza (pico)",     poder: 35000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Gildarts",        poder: 38000, emoji: "💥", tipo: "ataque" },
        { nome: "Gray (Iced Shell)", poder: 30000, emoji: "❄️", tipo: "ataque" },
        { nome: "Mavis (Fairy Heart)", poder: 40000, emoji: "🌸", tipo: "suporte" },
        { nome: "Laxus",           poder: 32000, emoji: "⚡", tipo: "ataque" },
        { nome: "Lucy (Fairy Sphere)", poder: 28000, emoji: "⭐", tipo: "suporte" },
      ],
    }
  },

  // ══ BLACK CLOVER ══════════════════════════════════════════════
  "Black Clover": {
    emoji: "☘️",
    sagas: {
      "Saga dos Cavaleiros Mágicos": [
        { nome: "Julius Novachrono",  poder: 18000, emoji: "⏰", tipo: "ataque" },
        { nome: "Yami Sukehiro",      poder: 16000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Fuegoleon",          poder: 14000, emoji: "🔥", tipo: "ataque" },
        { nome: "Nozel Silva",        poder: 13000, emoji: "💧", tipo: "ataque" },
        { nome: "Mereoleona",         poder: 15000, emoji: "🔥", tipo: "ataque" },
        { nome: "Asta (5 folhas)",    poder: 9000,  emoji: "☘️", tipo: "ataque" },
        { nome: "Yuno",               poder: 10000, emoji: "🌪️", tipo: "ataque" },
        { nome: "Noelle",             poder: 7000,  emoji: "💧", tipo: "ataque" },
        { nome: "Luck Voltia",        poder: 8000,  emoji: "⚡", tipo: "ataque" },
        { nome: "Finral",             poder: 6000,  emoji: "🌀", tipo: "suporte" },
        { nome: "Gauche",             poder: 7500,  emoji: "🪞", tipo: "ataque" },
      ],
      "Reencarnação dos Elfos": [
        { nome: "Licht",              poder: 25000, emoji: "☀️", tipo: "ataque" },
        { nome: "Patolli (Elfo)",     poder: 23000, emoji: "🌿", tipo: "ataque" },
        { nome: "Asta (Devil Union)", poder: 20000, emoji: "☘️", tipo: "ataque" },
        { nome: "Yuno (Spirit Dive)", poder: 19000, emoji: "🌪️", tipo: "ataque" },
        { nome: "Yami",               poder: 22000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Nozel",              poder: 17000, emoji: "💧", tipo: "ataque" },
        { nome: "Fuegoleon",          poder: 18000, emoji: "🔥", tipo: "ataque" },
        { nome: "Mereoleona",         poder: 20000, emoji: "🦁", tipo: "ataque" },
        { nome: "Mimosa (healer)",    poder: 12000, emoji: "🌺", tipo: "suporte" },
        { nome: "Rill Boismortier",   poder: 16000, emoji: "🎨", tipo: "ataque" },
        { nome: "Noelle (Valkyrie)",  poder: 15000, emoji: "💧", tipo: "ataque" },
      ],
      "Saga do Reino da Espada": [
        { nome: "Asta (Devil Union total)", poder: 38000, emoji: "😈", tipo: "ataque" },
        { nome: "Yuno (Príncipe)",    poder: 35000, emoji: "🌪️", tipo: "ataque" },
        { nome: "Lucifero",           poder: 45000, emoji: "😈", tipo: "ataque" },
        { nome: "Dante Zogratis",     poder: 32000, emoji: "🧟", tipo: "ataque" },
        { nome: "Zenon Zogratis",     poder: 30000, emoji: "💀", tipo: "ataque" },
        { nome: "Vanica Zogratis",    poder: 28000, emoji: "😈", tipo: "ataque" },
        { nome: "Megicula",           poder: 40000, emoji: "🩸", tipo: "ataque" },
        { nome: "Yami (liberado)",    poder: 33000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Nacht",              poder: 27000, emoji: "🌑", tipo: "ataque" },
        { nome: "Magna (equalized)",  poder: 25000, emoji: "🔥", tipo: "ataque" },
        { nome: "Noelle (Warrior Goddess)", poder: 26000, emoji: "💧", tipo: "ataque" },
      ],
    }
  },

  // ══ SEVEN DEADLY SINS ═════════════════════════════════════════
  "Seven Deadly Sins": {
    emoji: "🦁",
    sagas: {
      "Saga de Liones": [
        { nome: "Meliodas",        poder: 20000, emoji: "🐉", tipo: "ataque" },
        { nome: "Escanor",         poder: 18000, emoji: "☀️", tipo: "ataque" },
        { nome: "Ban",             poder: 15000, emoji: "🍺", tipo: "tank" },
        { nome: "King",            poder: 13000, emoji: "🧚", tipo: "suporte" },
        { nome: "Diane",           poder: 12000, emoji: "🌍", tipo: "tank" },
        { nome: "Hendrickson",     poder: 14000, emoji: "💀", tipo: "ataque" },
        { nome: "Gilthunder",      poder: 10000, emoji: "⚡", tipo: "ataque" },
        { nome: "Dreyfus",         poder: 9000,  emoji: "🗡️", tipo: "ataque" },
        { nome: "Vivian",          poder: 8000,  emoji: "🔮", tipo: "suporte" },
        { nome: "Howzer",          poder: 7500,  emoji: "💨", tipo: "ataque" },
        { nome: "Merlin",          poder: 16000, emoji: "🪄", tipo: "suporte" },
      ],
      "Saga dos Dez Mandamentos": [
        { nome: "Escanor (The One)", poder: 35000, emoji: "☀️", tipo: "ataque" },
        { nome: "Meliodas (Ressurreto)", poder: 34000, emoji: "🐉", tipo: "ataque" },
        { nome: "Zeldris",         poder: 28000, emoji: "🗡️", tipo: "ataque" },
        { nome: "Estarossa",       poder: 25000, emoji: "❤️", tipo: "ataque" },
        { nome: "Ban (Purgatorio)", poder: 22000, emoji: "🍺", tipo: "tank" },
        { nome: "Gloxinia",        poder: 20000, emoji: "🌺", tipo: "ataque" },
        { nome: "Drole",           poder: 20000, emoji: "🕺", tipo: "tank" },
        { nome: "Derieri",         poder: 18000, emoji: "👊", tipo: "ataque" },
        { nome: "Monspiet",        poder: 18000, emoji: "🔥", tipo: "ataque" },
        { nome: "Melascula",       poder: 16000, emoji: "🐍", tipo: "ataque" },
        { nome: "Galand",          poder: 15000, emoji: "🪓", tipo: "ataque" },
      ],
      "Saga do Rei Demônio": [
        { nome: "Meliodas (Rei Demônio)", poder: 55000, emoji: "🐉", tipo: "ataque" },
        { nome: "Zeldris (Rei Demônio)", poder: 52000, emoji: "🗡️", tipo: "ataque" },
        { nome: "Escanor (The One Eternal)", poder: 50000, emoji: "☀️", tipo: "ataque" },
        { nome: "Ban (Cor liberado)", poder: 45000, emoji: "🍺", tipo: "tank" },
        { nome: "Elizabeth (Deusa)", poder: 40000, emoji: "👼", tipo: "suporte" },
        { nome: "Mael com Grace",   poder: 42000, emoji: "⚡", tipo: "ataque" },
        { nome: "Merlin (Absolute Cancel)", poder: 38000, emoji: "🪄", tipo: "suporte" },
        { nome: "King (alas completas)", poder: 35000, emoji: "🧚", tipo: "ataque" },
        { nome: "Diane (Dançarina da Terra)", poder: 32000, emoji: "🌍", tipo: "tank" },
        { nome: "Gowther",          poder: 30000, emoji: "🏹", tipo: "suporte" },
        { nome: "Arthur (Camelot)", poder: 48000, emoji: "👑", tipo: "ataque" },
      ],
    }
  },

  // ══ BAKI ══════════════════════════════════════════════════════
  "Baki": {
    emoji: "💪",
    sagas: {
      "Saga dos Prisioneiros da Morte": [
        { nome: "Yujiro Hanma",    poder: 20000, emoji: "👹", tipo: "ataque" },
        { nome: "Baki Hanma",      poder: 14000, emoji: "💪", tipo: "ataque" },
        { nome: "Doppo Orochi",    poder: 12000, emoji: "🥋", tipo: "ataque" },
        { nome: "Spec",            poder: 13000, emoji: "☠️", tipo: "ataque" },
        { nome: "Sikorsky",        poder: 11000, emoji: "🐻", tipo: "ataque" },
        { nome: "Dorian",          poder: 12500, emoji: "🥊", tipo: "ataque" },
        { nome: "Doyle",           poder: 11500, emoji: "🎩", tipo: "ataque" },
        { nome: "Hanayama Kaoru",  poder: 13500, emoji: "🗿", tipo: "tank" },
        { nome: "Retsu Kaioh",     poder: 11000, emoji: "🐉", tipo: "ataque" },
        { nome: "Katsumi Orochi",  poder: 10000, emoji: "🥋", tipo: "ataque" },
        { nome: "Gerry Strydum",   poder: 10500, emoji: "🔫", tipo: "ataque" },
      ],
      "Saga de Musashi e Pickle": [
        { nome: "Yujiro Hanma",    poder: 22000, emoji: "👹", tipo: "ataque" },
        { nome: "Miyamoto Musashi (clone)", poder: 18000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Pickle",          poder: 17000, emoji: "🦕", tipo: "tank" },
        { nome: "Baki (adulto)",   poder: 16000, emoji: "💪", tipo: "ataque" },
        { nome: "Jack Hanma",      poder: 15000, emoji: "🦷", tipo: "tank" },
        { nome: "Oliva",           poder: 14500, emoji: "🏋️", tipo: "tank" },
        { nome: "Retsu (Musashi)", poder: 13500, emoji: "🐉", tipo: "ataque" },
        { nome: "Nomi no Sukune II", poder: 13000, emoji: "🏆", tipo: "ataque" },
        { nome: "Hanayama",        poder: 14000, emoji: "🗿", tipo: "tank" },
        { nome: "Doppo",           poder: 12500, emoji: "🥋", tipo: "ataque" },
        { nome: "Kaioh Kaku",      poder: 15500, emoji: "☯️", tipo: "ataque" },
      ],
    }
  },

  // ══ CHAINSAW MAN ══════════════════════════════════════════════
  "Chainsaw Man": {
    emoji: "⛓️",
    sagas: {
      "Saga da Divisão 4": [
        { nome: "Makima (Controle)", poder: 25000, emoji: "🎯", tipo: "ataque" },
        { nome: "Denji (Chainsaw)", poder: 18000, emoji: "⛓️", tipo: "ataque" },
        { nome: "Quanxi",           poder: 16000, emoji: "🏹", tipo: "ataque" },
        { nome: "Santa Claus",      poder: 14000, emoji: "🎅", tipo: "ataque" },
        { nome: "Reze (Bomb)",      poder: 15000, emoji: "💣", tipo: "ataque" },
        { nome: "Katana Man",       poder: 12000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Beam",             poder: 11000, emoji: "🦈", tipo: "ataque" },
        { nome: "Aki (Futuro)",     poder: 13000, emoji: "🪶", tipo: "ataque" },
        { nome: "Power",            poder: 10000, emoji: "🩸", tipo: "ataque" },
        { nome: "Himeno",           poder: 9000,  emoji: "🌫️", tipo: "ataque" },
        { nome: "Kishibe",          poder: 14000, emoji: "🔪", tipo: "ataque" },
      ],
      "Saga de Makima — Apocalipse": [
        { nome: "Pochita (Chainsaw Devil)", poder: 35000, emoji: "🐶", tipo: "ataque" },
        { nome: "Makima (peak)",    poder: 32000, emoji: "🎯", tipo: "ataque" },
        { nome: "Denji (Pochita fundido)", poder: 30000, emoji: "⛓️", tipo: "ataque" },
        { nome: "Yoru (War Devil)", poder: 22000, emoji: "🪖", tipo: "ataque" },
        { nome: "Power Ressurreto", poder: 18000, emoji: "🩸", tipo: "ataque" },
        { nome: "Asa Mitaka",       poder: 14000, emoji: "🌊", tipo: "ataque" },
        { nome: "Fumiko Mifune",    poder: 12000, emoji: "🌙", tipo: "ataque" },
        { nome: "Nayuta",           poder: 25000, emoji: "🎯", tipo: "ataque" },
        { nome: "Fami",             poder: 20000, emoji: "🍴", tipo: "ataque" },
        { nome: "Barem",            poder: 17000, emoji: "🔫", tipo: "ataque" },
        { nome: "Flamethrower",     poder: 10000, emoji: "🔥", tipo: "ataque" },
      ],
    }
  },

  // ══ SHAMAN KING ═══════════════════════════════════════════════
  "Shaman King": {
    emoji: "🔮",
    sagas: {
      "Torneio Shaman": [
        { nome: "Hao (Zeke)",      poder: 30000, emoji: "🔥", tipo: "ataque" },
        { nome: "Yoh Asakura",     poder: 14000, emoji: "🎵", tipo: "ataque" },
        { nome: "Ren Tao",         poder: 13000, emoji: "⚡", tipo: "ataque" },
        { nome: "Horohoro",        poder: 11000, emoji: "❄️", tipo: "ataque" },
        { nome: "Faust VIII",      poder: 12000, emoji: "☠️", tipo: "ataque" },
        { nome: "Jeanne de Ferro", poder: 16000, emoji: "✝️", tipo: "ataque" },
        { nome: "Marco",           poder: 14500, emoji: "🔱", tipo: "suporte" },
        { nome: "Boris",           poder: 13500, emoji: "🩸", tipo: "ataque" },
        { nome: "Lyserg",          poder: 10000, emoji: "🔍", tipo: "ataque" },
        { nome: "Chocolove",       poder: 9500,  emoji: "🍫", tipo: "suporte" },
        { nome: "Silva",           poder: 11000, emoji: "🐻", tipo: "ataque" },
      ],
      "Saga dos Shamans X — Grande Espírito": [
        { nome: "Hao (Grande Espírito)", poder: 50000, emoji: "🔥", tipo: "ataque" },
        { nome: "Yoh (resolve)",  poder: 28000, emoji: "🎵", tipo: "ataque" },
        { nome: "Ren (pico)",     poder: 25000, emoji: "⚡", tipo: "ataque" },
        { nome: "Jeanne (Arma Sagrada)", poder: 24000, emoji: "✝️", tipo: "ataque" },
        { nome: "Manta (olho)",   poder: 8000,  emoji: "👓", tipo: "suporte" },
        { nome: "Lyserg (Zeruel)", poder: 20000, emoji: "🔍", tipo: "ataque" },
        { nome: "Horohoro (Usurai)", poder: 22000, emoji: "❄️", tipo: "ataque" },
        { nome: "Anna Kyoyama",   poder: 18000, emoji: "📿", tipo: "suporte" },
        { nome: "Goldva",         poder: 30000, emoji: "👑", tipo: "ataque" },
        { nome: "Faust (Eliza)",  poder: 19000, emoji: "☠️", tipo: "ataque" },
        { nome: "Sati Saigan",    poder: 22000, emoji: "🌸", tipo: "suporte" },
      ],
    }
  },

  // ══ SOUL EATER ════════════════════════════════════════════════
  "Soul Eater": {
    emoji: "🌙",
    sagas: {
      "Saga de Arachnophobia": [
        { nome: "Arachne",         poder: 18000, emoji: "🕷️", tipo: "ataque" },
        { nome: "Black Star (Manji)", poder: 15000, emoji: "⭐", tipo: "ataque" },
        { nome: "Death the Kid",   poder: 14000, emoji: "💀", tipo: "ataque" },
        { nome: "Maka + Soul",     poder: 13000, emoji: "📚", tipo: "ataque" },
        { nome: "Giriko",          poder: 12000, emoji: "⚙️", tipo: "ataque" },
        { nome: "Free",            poder: 11000, emoji: "🐺", tipo: "ataque" },
        { nome: "Mosquito",        poder: 13500, emoji: "🦟", tipo: "ataque" },
        { nome: "Crona",           poder: 12500, emoji: "🩸", tipo: "ataque" },
        { nome: "Medusa",          poder: 14000, emoji: "🐍", tipo: "ataque" },
        { nome: "Stein",           poder: 15000, emoji: "🔩", tipo: "ataque" },
        { nome: "Mifune",          poder: 13000, emoji: "⚔️", tipo: "ataque" },
      ],
      "Kishin Asura": [
        { nome: "Asura (Kishin)",  poder: 30000, emoji: "😱", tipo: "ataque" },
        { nome: "Lord Death",      poder: 28000, emoji: "💀", tipo: "ataque" },
        { nome: "Black Star (Majin)", poder: 22000, emoji: "⭐", tipo: "ataque" },
        { nome: "Death the Kid (Simétrico)", poder: 24000, emoji: "🔱", tipo: "ataque" },
        { nome: "Maka (Anti-Demon Wavelength)", poder: 20000, emoji: "📚", tipo: "ataque" },
        { nome: "Soul Eater (True Demon)", poder: 18000, emoji: "🎵", tipo: "ataque" },
        { nome: "Stein (Madness)", poder: 17000, emoji: "🔩", tipo: "ataque" },
        { nome: "Medusa (final)",  poder: 16000, emoji: "🐍", tipo: "ataque" },
        { nome: "Crona (Ragnarok)", poder: 20000, emoji: "🩸", tipo: "ataque" },
        { nome: "Gopher",          poder: 14000, emoji: "💜", tipo: "ataque" },
        { nome: "Giriko (Vajra)", poder: 15000, emoji: "⚙️", tipo: "ataque" },
      ],
    }
  },

  // ══ AKAME GA KILL ══════════════════════════════════════════════
  "Akame ga Kill": {
    emoji: "🗡️",
    sagas: {
      "Night Raid vs Corte Imperial": [
        { nome: "Esdeath",         poder: 20000, emoji: "❄️", tipo: "ataque" },
        { nome: "Budo",            poder: 18000, emoji: "⚡", tipo: "ataque" },
        { nome: "Akame",           poder: 16000, emoji: "🗡️", tipo: "ataque" },
        { nome: "Bulat (Incursio)", poder: 14000, emoji: "🛡️", tipo: "tank" },
        { nome: "Leone",           poder: 12000, emoji: "🦁", tipo: "ataque" },
        { nome: "Mine (Pumpkin)",  poder: 11000, emoji: "🔫", tipo: "ataque" },
        { nome: "Tatsumi (Incursio)", poder: 13000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Sheele",          poder: 10000, emoji: "✂️", tipo: "ataque" },
        { nome: "Lubbock",         poder: 9000,  emoji: "🧵", tipo: "ataque" },
        { nome: "Susanoo",         poder: 15000, emoji: "⛩️", tipo: "ataque" },
        { nome: "Najenda",         poder: 8000,  emoji: "💀", tipo: "suporte" },
      ],
      "Batalha Final — Murasame": [
        { nome: "Akame (Murasame completo)", poder: 28000, emoji: "🗡️", tipo: "ataque" },
        { nome: "Esdeath (peak)", poder: 26000, emoji: "❄️", tipo: "ataque" },
        { nome: "Tatsumi (Dragão)", poder: 24000, emoji: "🐉", tipo: "ataque" },
        { nome: "Leone (final)",   poder: 18000, emoji: "🦁", tipo: "ataque" },
        { nome: "Wave (Grand Chariot)", poder: 20000, emoji: "🌊", tipo: "ataque" },
        { nome: "Kurome (Yatsufusa)", poder: 17000, emoji: "💀", tipo: "ataque" },
        { nome: "Run",             poder: 14000, emoji: "🕊️", tipo: "ataque" },
        { nome: "Honest",          poder: 5000,  emoji: "😈", tipo: "ataque" },
        { nome: "Bolic",           poder: 6000,  emoji: "😒", tipo: "ataque" },
        { nome: "Seryu",           poder: 13000, emoji: "⚖️", tipo: "ataque" },
        { nome: "Cosmina",         poder: 12000, emoji: "🌸", tipo: "ataque" },
      ],
    }
  },

  // ══ FIRE FORCE ════════════════════════════════════════════════
  "Fire Force": {
    emoji: "🔥",
    sagas: {
      "Saga do 8° Regimento — Adolla": [
        { nome: "Shinra (Adolla Burst)", poder: 18000, emoji: "😈", tipo: "ataque" },
        { nome: "Captain Burns",  poder: 20000, emoji: "🔥", tipo: "ataque" },
        { nome: "Joker",          poder: 17000, emoji: "🃏", tipo: "ataque" },
        { nome: "Sho Kusakabe",   poder: 22000, emoji: "❄️", tipo: "ataque" },
        { nome: "Charon",         poder: 16000, emoji: "🛡️", tipo: "tank" },
        { nome: "Haumea",         poder: 15000, emoji: "⚡", tipo: "ataque" },
        { nome: "Benimaru",       poder: 21000, emoji: "🔥", tipo: "ataque" },
        { nome: "Arthur",         poder: 14000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Maki",           poder: 12000, emoji: "💪", tipo: "ataque" },
        { nome: "Tamaki",         poder: 10000, emoji: "🐱", tipo: "ataque" },
        { nome: "Giovanni",       poder: 13000, emoji: "🧪", tipo: "ataque" },
      ],
      "Saga da Evangelista — Grande Incêndio": [
        { nome: "Shinra (velocidade da luz)", poder: 35000, emoji: "😈", tipo: "ataque" },
        { nome: "Sho (Severed Universe)", poder: 32000, emoji: "❄️", tipo: "ataque" },
        { nome: "Burns (Sacerdote Olho)", poder: 30000, emoji: "🔥", tipo: "ataque" },
        { nome: "Benimaru (pico)", poder: 33000, emoji: "🔥", tipo: "ataque" },
        { nome: "Charon",          poder: 24000, emoji: "🛡️", tipo: "tank" },
        { nome: "Inca Kasugatani", poder: 22000, emoji: "🎯", tipo: "ataque" },
        { nome: "Tempe",           poder: 20000, emoji: "🌪️", tipo: "ataque" },
        { nome: "Schop",           poder: 18000, emoji: "🌀", tipo: "ataque" },
        { nome: "Arrow",           poder: 19000, emoji: "🏹", tipo: "ataque" },
        { nome: "Konro (recuperado)", poder: 21000, emoji: "🔥", tipo: "ataque" },
        { nome: "Joker",           poder: 25000, emoji: "🃏", tipo: "ataque" },
      ],
    }
  },

  // ══ RUROUNI KENSHIN ═══════════════════════════════════════════
  "Rurouni Kenshin": {
    emoji: "⚔️",
    sagas: {
      "Saga de Kyoto — Shishio": [
        { nome: "Shishio Makoto",  poder: 14000, emoji: "🔥", tipo: "ataque" },
        { nome: "Kenshin (Battoujutsu)", poder: 13500, emoji: "⚔️", tipo: "ataque" },
        { nome: "Saito Hajime",   poder: 12000, emoji: "🐺", tipo: "ataque" },
        { nome: "Aoshi Shinomori", poder: 11500, emoji: "🪭", tipo: "ataque" },
        { nome: "Sojiro Seta",    poder: 13000, emoji: "😊", tipo: "ataque" },
        { nome: "Yumi",           poder: 5000,  emoji: "💃", tipo: "suporte" },
        { nome: "Cho",            poder: 9000,  emoji: "⚔️", tipo: "ataque" },
        { nome: "Usui",           poder: 10000, emoji: "👁️", tipo: "ataque" },
        { nome: "Kaoru",          poder: 4000,  emoji: "🌸", tipo: "suporte" },
        { nome: "Yahiko",         poder: 5000,  emoji: "🥋", tipo: "ataque" },
        { nome: "Misao",          poder: 6000,  emoji: "⚔️", tipo: "ataque" },
      ],
      "Saga Jinchu — Enishi": [
        { nome: "Kenshin (Hiten restaurado)", poder: 15000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Enishi Yukishiro", poder: 14500, emoji: "🌸", tipo: "ataque" },
        { nome: "Saito",          poder: 12500, emoji: "🐺", tipo: "ataque" },
        { nome: "Aoshi",          poder: 12000, emoji: "🪭", tipo: "ataque" },
        { nome: "Gein",           poder: 10000, emoji: "🎭", tipo: "ataque" },
        { nome: "Otowa",          poder: 11000, emoji: "💀", tipo: "ataque" },
        { nome: "Inui",           poder: 10500, emoji: "🦷", tipo: "ataque" },
        { nome: "Kaoru",          poder: 5000,  emoji: "🌸", tipo: "suporte" },
        { nome: "Yahiko",         poder: 7000,  emoji: "🥋", tipo: "ataque" },
        { nome: "Sano",           poder: 9000,  emoji: "🥊", tipo: "ataque" },
        { nome: "Megumi",         poder: 4000,  emoji: "💊", tipo: "suporte" },
      ],
    }
  },

  // ══ FIST OF THE NORTH STAR ════════════════════════════════════
  "Fist of the North Star": {
    emoji: "☠️",
    sagas: {
      "Saga de Shin — Hokuto vs Nanto": [
        { nome: "Kenshiro",       poder: 14000, emoji: "💀", tipo: "ataque" },
        { nome: "Shin (Nanto)",   poder: 13000, emoji: "🌟", tipo: "ataque" },
        { nome: "Rei (Nanto Suicho)", poder: 12000, emoji: "🌊", tipo: "ataque" },
        { nome: "Jagi",           poder: 9000,  emoji: "😈", tipo: "ataque" },
        { nome: "Toki",           poder: 11000, emoji: "☀️", tipo: "ataque" },
        { nome: "Yuda",           poder: 10000, emoji: "💄", tipo: "ataque" },
        { nome: "Mamiya",         poder: 6000,  emoji: "🔗", tipo: "suporte" },
        { nome: "Bat",            poder: 4000,  emoji: "🦇", tipo: "suporte" },
        { nome: "Lin",            poder: 2000,  emoji: "👧", tipo: "suporte" },
        { nome: "Amar (guerreiros)", poder: 5000, emoji: "🌾", tipo: "ataque" },
        { nome: "Raoh (revelado)", poder: 16000, emoji: "👑", tipo: "ataque" },
      ],
      "Saga de Raoh — Deus da Batalha": [
        { nome: "Kenshiro (peak)", poder: 20000, emoji: "💀", tipo: "ataque" },
        { nome: "Raoh",           poder: 19000, emoji: "👑", tipo: "ataque" },
        { nome: "Toki (doente)",  poder: 15000, emoji: "☀️", tipo: "ataque" },
        { nome: "Rei (Nanto)",    poder: 13500, emoji: "🌊", tipo: "ataque" },
        { nome: "Juza",           poder: 12000, emoji: "🌀", tipo: "ataque" },
        { nome: "Fudo",           poder: 11000, emoji: "🌲", tipo: "ataque" },
        { nome: "Falco",          poder: 11500, emoji: "🦅", tipo: "ataque" },
        { nome: "Rihaku",         poder: 9000,  emoji: "🐢", tipo: "suporte" },
        { nome: "Mamiya",         poder: 7000,  emoji: "🔗", tipo: "suporte" },
        { nome: "Bat (adulto)",   poder: 6000,  emoji: "🦇", tipo: "suporte" },
        { nome: "Koryu",          poder: 10000, emoji: "🔥", tipo: "ataque" },
      ],
    }
  },

  // ══ MOB PSYCHO 100 ════════════════════════════════════════════
  "Mob Psycho 100": {
    emoji: "👤",
    sagas: {
      "Divisão Claw": [
        { nome: "Mob (100% Raiva)", poder: 18000, emoji: "👤", tipo: "ataque" },
        { nome: "Shimazaki",       poder: 14000, emoji: "💨", tipo: "ataque" },
        { nome: "Touichirou Suzuki", poder: 16000, emoji: "⚡", tipo: "ataque" },
        { nome: "Minegishi",       poder: 12000, emoji: "🌿", tipo: "ataque" },
        { nome: "Serizawa",        poder: 11000, emoji: "☂️", tipo: "ataque" },
        { nome: "Reigen",          poder: 9000,  emoji: "💼", tipo: "suporte" },
        { nome: "Dimple",          poder: 8000,  emoji: "👻", tipo: "suporte" },
        { nome: "Teruki Hanazawa", poder: 10000, emoji: "⚡", tipo: "ataque" },
        { nome: "Ritsu (Mob irmão)", poder: 7000, emoji: "🧊", tipo: "ataque" },
        { nome: "Terada",          poder: 6000,  emoji: "🏋️", tipo: "ataque" },
        { nome: "Tsuchiya",        poder: 7500,  emoji: "💢", tipo: "ataque" },
      ],
      "100% Arc — Separação": [
        { nome: "Mob (100% Sadness)", poder: 22000, emoji: "😢", tipo: "ataque" },
        { nome: "Mob (???%)",        poder: 30000, emoji: "👤", tipo: "ataque" },
        { nome: "Mogami (espírito)", poder: 18000, emoji: "😈", tipo: "ataque" },
        { nome: "Shou Suzuki",       poder: 14000, emoji: "🔥", tipo: "ataque" },
        { nome: "Dimple (Deus Arroz)", poder: 16000, emoji: "🌾", tipo: "suporte" },
        { nome: "Reigen (absorveu Mob)", poder: 12000, emoji: "💼", tipo: "suporte" },
        { nome: "Teruki",            poder: 11000, emoji: "⚡", tipo: "ataque" },
        { nome: "Serizawa",          poder: 10000, emoji: "☂️", tipo: "ataque" },
        { nome: "Ritsu",             poder: 9000,  emoji: "🧊", tipo: "ataque" },
        { nome: "Mezato",            poder: 5000,  emoji: "📸", tipo: "suporte" },
        { nome: "Tsubomi",           poder: 3000,  emoji: "🌸", tipo: "suporte" },
      ],
    }
  },

  // ══ VINLAND SAGA ══════════════════════════════════════════════
  "Vinland Saga": {
    emoji: "🪓",
    sagas: {
      "Saga Viking — Askeladd": [
        { nome: "Thorkell",       poder: 16000, emoji: "🪓", tipo: "tank" },
        { nome: "Askeladd",       poder: 14000, emoji: "🐺", tipo: "ataque" },
        { nome: "Thors",          poder: 15000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Bjorn",          poder: 11000, emoji: "🐻", tipo: "ataque" },
        { nome: "Floki",          poder: 9000,  emoji: "🦊", tipo: "ataque" },
        { nome: "Thorfinn (jovem)", poder: 8000, emoji: "🗡️", tipo: "ataque" },
        { nome: "Canute (príncipe)", poder: 6000, emoji: "👑", tipo: "suporte" },
        { nome: "Atli",           poder: 7000,  emoji: "⚔️", tipo: "ataque" },
        { nome: "Leif",           poder: 5000,  emoji: "🌍", tipo: "suporte" },
        { nome: "Willibald",      poder: 3000,  emoji: "📖", tipo: "suporte" },
        { nome: "Ragnar",         poder: 4000,  emoji: "🛡️", tipo: "suporte" },
      ],
      "Saga da Fazenda e Redenção": [
        { nome: "Thorfinn (adulto)", poder: 18000, emoji: "🗡️", tipo: "ataque" },
        { nome: "Thorkell",          poder: 17000, emoji: "🪓", tipo: "tank" },
        { nome: "Snake",             poder: 14000, emoji: "🐍", tipo: "ataque" },
        { nome: "Wulf",              poder: 12000, emoji: "🐺", tipo: "ataque" },
        { nome: "Einar",             poder: 9000,  emoji: "🌾", tipo: "ataque" },
        { nome: "Ketil",             poder: 8000,  emoji: "💰", tipo: "ataque" },
        { nome: "Olmar",             poder: 7000,  emoji: "⚔️", tipo: "ataque" },
        { nome: "Gardar",            poder: 10000, emoji: "🔗", tipo: "ataque" },
        { nome: "Fox",               poder: 9500,  emoji: "🦊", tipo: "ataque" },
        { nome: "Badger",            poder: 9000,  emoji: "🦡", tipo: "ataque" },
        { nome: "Sigrid",            poder: 5000,  emoji: "🌻", tipo: "suporte" },
      ],
    }
  },

  // ══ BERSERK ═══════════════════════════════════════════════════
  "Berserk": {
    emoji: "⚔️",
    sagas: {
      "Saga do Falcão Dourado": [
        { nome: "Griffith",       poder: 16000, emoji: "🦅", tipo: "ataque" },
        { nome: "Guts (Espadachim Negro)", poder: 15000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Zodd (Apostolo)", poder: 14000, emoji: "🐂", tipo: "tank" },
        { nome: "Casca",          poder: 10000, emoji: "🛡️", tipo: "suporte" },
        { nome: "Judeau",         poder: 9000,  emoji: "🎯", tipo: "ataque" },
        { nome: "Pippin",         poder: 8500,  emoji: "💪", tipo: "tank" },
        { nome: "Silat",          poder: 8000,  emoji: "🥷", tipo: "ataque" },
        { nome: "Corkus",         poder: 7000,  emoji: "⚙️", tipo: "ataque" },
        { nome: "Rickert",        poder: 6000,  emoji: "🏹", tipo: "suporte" },
        { nome: "Gennon",         poder: 5000,  emoji: "💰", tipo: "ataque" },
        { nome: "Adon",           poder: 7500,  emoji: "🏆", tipo: "ataque" },
      ],
      "O Eclipse e Era das Trevas": [
        { nome: "Femto (Griffith)", poder: 30000, emoji: "🦅", tipo: "ataque" },
        { nome: "Guts Marcado",    poder: 20000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Skull Knight",    poder: 25000, emoji: "💀", tipo: "ataque" },
        { nome: "Zodd",            poder: 18000, emoji: "🐂", tipo: "tank" },
        { nome: "Void",            poder: 28000, emoji: "👁️", tipo: "ataque" },
        { nome: "Slan",            poder: 26000, emoji: "🌹", tipo: "ataque" },
        { nome: "Ubik",            poder: 24000, emoji: "🕊️", tipo: "ataque" },
        { nome: "Conrad",          poder: 23000, emoji: "🐀", tipo: "ataque" },
        { nome: "Grunbeld",        poder: 17000, emoji: "🔥", tipo: "tank" },
        { nome: "Rakshas",         poder: 15000, emoji: "🕷️", tipo: "ataque" },
        { nome: "Serpico",         poder: 14000, emoji: "💨", tipo: "ataque" },
      ],
    }
  },

  // ══ OVERLORD ══════════════════════════════════════════════════
  "Overlord": {
    emoji: "💀",
    sagas: {
      "Saga de Nazarick — Ascensão": [
        { nome: "Ainz Ooal Gown",  poder: 35000, emoji: "💀", tipo: "ataque" },
        { nome: "Albedo",          poder: 22000, emoji: "😈", tipo: "tank" },
        { nome: "Shalltear Bloodfallen", poder: 24000, emoji: "🩸", tipo: "ataque" },
        { nome: "Cocytus",         poder: 21000, emoji: "❄️", tipo: "tank" },
        { nome: "Demiurge",        poder: 20000, emoji: "😈", tipo: "ataque" },
        { nome: "Mare",            poder: 19000, emoji: "🌿", tipo: "ataque" },
        { nome: "Aura",            poder: 18000, emoji: "🏹", tipo: "ataque" },
        { nome: "Victim",          poder: 16000, emoji: "👼", tipo: "suporte" },
        { nome: "Sebas",           poder: 17000, emoji: "🎩", tipo: "ataque" },
        { nome: "Lupusregina",     poder: 14000, emoji: "🐺", tipo: "ataque" },
        { nome: "Entoma",          poder: 13000, emoji: "🕷️", tipo: "ataque" },
      ],
      "Saga do Re-Estize": [
        { nome: "Ainz (Wish Upon a Star)", poder: 40000, emoji: "💀", tipo: "ataque" },
        { nome: "Shalltear (desbloqueada)", poder: 26000, emoji: "🩸", tipo: "ataque" },
        { nome: "Albedo (Guardião)", poder: 23000, emoji: "😈", tipo: "ataque" },
        { nome: "Evileye",         poder: 12000, emoji: "👁️", tipo: "ataque" },
        { nome: "Lakyus",          poder: 11000, emoji: "💜", tipo: "ataque" },
        { nome: "Gazef Stronoff",  poder: 10000, emoji: "⚔️", tipo: "ataque" },
        { nome: "Brain Unglaus",   poder: 9000,  emoji: "🧠", tipo: "ataque" },
        { nome: "Climb",           poder: 7000,  emoji: "🪜", tipo: "ataque" },
        { nome: "Gagaran",         poder: 11500, emoji: "🔨", tipo: "tank" },
        { nome: "Tia & Tina",      poder: 10000, emoji: "🐱", tipo: "ataque" },
        { nome: "Azuth Aindra",    poder: 12500, emoji: "🃏", tipo: "ataque" },
      ],
    }
  },

  // ══ HAJIME NO IPPO ════════════════════════════════════════════
  "Hajime no Ippo": {
    emoji: "🥊",
    sagas: {
      "Campeonato Japonês de Boxe": [
        { nome: "Takamura",        poder: 18000, emoji: "🐻", tipo: "ataque" },
        { nome: "Date Eiji",       poder: 16000, emoji: "🎯", tipo: "ataque" },
        { nome: "Miyata Ichirou",  poder: 14000, emoji: "💫", tipo: "ataque" },
        { nome: "Ippo Makunouchi", poder: 13000, emoji: "🥊", tipo: "ataque" },
        { nome: "Sendo",           poder: 13500, emoji: "🦁", tipo: "ataque" },
        { nome: "Kimura",          poder: 11000, emoji: "🐯", tipo: "ataque" },
        { nome: "Aoki",            poder: 10000, emoji: "🐸", tipo: "suporte" },
        { nome: "Mashiba",         poder: 12000, emoji: "🔪", tipo: "ataque" },
        { nome: "Volg Zangief",    poder: 13000, emoji: "🐺", tipo: "ataque" },
        { nome: "Jason Ozuma",     poder: 11500, emoji: "🌪️", tipo: "ataque" },
        { nome: "Kobashi",         poder: 8000,  emoji: "🛡️", tipo: "tank" },
      ],
      "Campeonato Mundial": [
        { nome: "Ricardo Martinez", poder: 22000, emoji: "👑", tipo: "ataque" },
        { nome: "Takamura (WBC)",  poder: 20000, emoji: "🐻", tipo: "ataque" },
        { nome: "Randy Boy Jr.",   poder: 18000, emoji: "🌟", tipo: "ataque" },
        { nome: "Ippo (Smash)",    poder: 17000, emoji: "🥊", tipo: "ataque" },
        { nome: "David Eagle",     poder: 19000, emoji: "🦅", tipo: "ataque" },
        { nome: "Sendo (México)",  poder: 16000, emoji: "🦁", tipo: "ataque" },
        { nome: "Sawamura",        poder: 15000, emoji: "🔥", tipo: "ataque" },
        { nome: "Woli",            poder: 15500, emoji: "🌍", tipo: "ataque" },
        { nome: "Miyata (título)", poder: 16000, emoji: "💫", tipo: "ataque" },
        { nome: "Shimabukuro",     poder: 14000, emoji: "🌊", tipo: "ataque" },
        { nome: "Itagaki",         poder: 13500, emoji: "🐆", tipo: "ataque" },
      ],
    }
  },

};
